/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the VariableVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableVersion{}

// VariableVersion struct for VariableVersion
type VariableVersion struct {
	Variable *Variable `json:"variable,omitempty"`
	Version *int32 `json:"version,omitempty"`
	// Encryption algorithm identifier, e.g. \"xsalsa20poly1305\". Sensitive only.
	Algo NullableString `json:"algo,omitempty"`
	// Identifier of the key-encryption-key that wrapped this value. Sensitive only.
	KeyId NullableString `json:"keyId,omitempty"`
	Nonce NullableString `json:"nonce,omitempty"`
	Ciphertext NullableString `json:"ciphertext,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	CreatedBy NullableUser `json:"createdBy,omitempty"`
	Id *string `json:"id,omitempty"`
	// Populate an encrypted (sensitive) value.
	Encrypted *string `json:"encrypted,omitempty"`
	// Populate a plaintext (non-sensitive) value.
	Plaintext *string `json:"plaintext,omitempty"`
}

// NewVariableVersion instantiates a new VariableVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableVersion() *VariableVersion {
	this := VariableVersion{}
	return &this
}

// NewVariableVersionWithDefaults instantiates a new VariableVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableVersionWithDefaults() *VariableVersion {
	this := VariableVersion{}
	return &this
}

// GetVariable returns the Variable field value if set, zero value otherwise.
func (o *VariableVersion) GetVariable() Variable {
	if o == nil || IsNil(o.Variable) {
		var ret Variable
		return ret
	}
	return *o.Variable
}

// GetVariableOk returns a tuple with the Variable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableVersion) GetVariableOk() (*Variable, bool) {
	if o == nil || IsNil(o.Variable) {
		return nil, false
	}
	return o.Variable, true
}

// HasVariable returns a boolean if a field has been set.
func (o *VariableVersion) HasVariable() bool {
	if o != nil && !IsNil(o.Variable) {
		return true
	}

	return false
}

// SetVariable gets a reference to the given Variable and assigns it to the Variable field.
func (o *VariableVersion) SetVariable(v Variable) {
	o.Variable = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *VariableVersion) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableVersion) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *VariableVersion) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *VariableVersion) SetVersion(v int32) {
	o.Version = &v
}

// GetAlgo returns the Algo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableVersion) GetAlgo() string {
	if o == nil || IsNil(o.Algo.Get()) {
		var ret string
		return ret
	}
	return *o.Algo.Get()
}

// GetAlgoOk returns a tuple with the Algo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableVersion) GetAlgoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Algo.Get(), o.Algo.IsSet()
}

// HasAlgo returns a boolean if a field has been set.
func (o *VariableVersion) HasAlgo() bool {
	if o != nil && o.Algo.IsSet() {
		return true
	}

	return false
}

// SetAlgo gets a reference to the given NullableString and assigns it to the Algo field.
func (o *VariableVersion) SetAlgo(v string) {
	o.Algo.Set(&v)
}
// SetAlgoNil sets the value for Algo to be an explicit nil
func (o *VariableVersion) SetAlgoNil() {
	o.Algo.Set(nil)
}

// UnsetAlgo ensures that no value is present for Algo, not even an explicit nil
func (o *VariableVersion) UnsetAlgo() {
	o.Algo.Unset()
}

// GetKeyId returns the KeyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableVersion) GetKeyId() string {
	if o == nil || IsNil(o.KeyId.Get()) {
		var ret string
		return ret
	}
	return *o.KeyId.Get()
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableVersion) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyId.Get(), o.KeyId.IsSet()
}

// HasKeyId returns a boolean if a field has been set.
func (o *VariableVersion) HasKeyId() bool {
	if o != nil && o.KeyId.IsSet() {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given NullableString and assigns it to the KeyId field.
func (o *VariableVersion) SetKeyId(v string) {
	o.KeyId.Set(&v)
}
// SetKeyIdNil sets the value for KeyId to be an explicit nil
func (o *VariableVersion) SetKeyIdNil() {
	o.KeyId.Set(nil)
}

// UnsetKeyId ensures that no value is present for KeyId, not even an explicit nil
func (o *VariableVersion) UnsetKeyId() {
	o.KeyId.Unset()
}

// GetNonce returns the Nonce field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableVersion) GetNonce() string {
	if o == nil || IsNil(o.Nonce.Get()) {
		var ret string
		return ret
	}
	return *o.Nonce.Get()
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableVersion) GetNonceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nonce.Get(), o.Nonce.IsSet()
}

// HasNonce returns a boolean if a field has been set.
func (o *VariableVersion) HasNonce() bool {
	if o != nil && o.Nonce.IsSet() {
		return true
	}

	return false
}

// SetNonce gets a reference to the given NullableString and assigns it to the Nonce field.
func (o *VariableVersion) SetNonce(v string) {
	o.Nonce.Set(&v)
}
// SetNonceNil sets the value for Nonce to be an explicit nil
func (o *VariableVersion) SetNonceNil() {
	o.Nonce.Set(nil)
}

// UnsetNonce ensures that no value is present for Nonce, not even an explicit nil
func (o *VariableVersion) UnsetNonce() {
	o.Nonce.Unset()
}

// GetCiphertext returns the Ciphertext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableVersion) GetCiphertext() string {
	if o == nil || IsNil(o.Ciphertext.Get()) {
		var ret string
		return ret
	}
	return *o.Ciphertext.Get()
}

// GetCiphertextOk returns a tuple with the Ciphertext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableVersion) GetCiphertextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ciphertext.Get(), o.Ciphertext.IsSet()
}

// HasCiphertext returns a boolean if a field has been set.
func (o *VariableVersion) HasCiphertext() bool {
	if o != nil && o.Ciphertext.IsSet() {
		return true
	}

	return false
}

// SetCiphertext gets a reference to the given NullableString and assigns it to the Ciphertext field.
func (o *VariableVersion) SetCiphertext(v string) {
	o.Ciphertext.Set(&v)
}
// SetCiphertextNil sets the value for Ciphertext to be an explicit nil
func (o *VariableVersion) SetCiphertextNil() {
	o.Ciphertext.Set(nil)
}

// UnsetCiphertext ensures that no value is present for Ciphertext, not even an explicit nil
func (o *VariableVersion) UnsetCiphertext() {
	o.Ciphertext.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *VariableVersion) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableVersion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *VariableVersion) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *VariableVersion) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableVersion) GetCreatedBy() User {
	if o == nil || IsNil(o.CreatedBy.Get()) {
		var ret User
		return ret
	}
	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableVersion) GetCreatedByOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *VariableVersion) HasCreatedBy() bool {
	if o != nil && o.CreatedBy.IsSet() {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given NullableUser and assigns it to the CreatedBy field.
func (o *VariableVersion) SetCreatedBy(v User) {
	o.CreatedBy.Set(&v)
}
// SetCreatedByNil sets the value for CreatedBy to be an explicit nil
func (o *VariableVersion) SetCreatedByNil() {
	o.CreatedBy.Set(nil)
}

// UnsetCreatedBy ensures that no value is present for CreatedBy, not even an explicit nil
func (o *VariableVersion) UnsetCreatedBy() {
	o.CreatedBy.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VariableVersion) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableVersion) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VariableVersion) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VariableVersion) SetId(v string) {
	o.Id = &v
}

// GetEncrypted returns the Encrypted field value if set, zero value otherwise.
func (o *VariableVersion) GetEncrypted() string {
	if o == nil || IsNil(o.Encrypted) {
		var ret string
		return ret
	}
	return *o.Encrypted
}

// GetEncryptedOk returns a tuple with the Encrypted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableVersion) GetEncryptedOk() (*string, bool) {
	if o == nil || IsNil(o.Encrypted) {
		return nil, false
	}
	return o.Encrypted, true
}

// HasEncrypted returns a boolean if a field has been set.
func (o *VariableVersion) HasEncrypted() bool {
	if o != nil && !IsNil(o.Encrypted) {
		return true
	}

	return false
}

// SetEncrypted gets a reference to the given string and assigns it to the Encrypted field.
func (o *VariableVersion) SetEncrypted(v string) {
	o.Encrypted = &v
}

// GetPlaintext returns the Plaintext field value if set, zero value otherwise.
func (o *VariableVersion) GetPlaintext() string {
	if o == nil || IsNil(o.Plaintext) {
		var ret string
		return ret
	}
	return *o.Plaintext
}

// GetPlaintextOk returns a tuple with the Plaintext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableVersion) GetPlaintextOk() (*string, bool) {
	if o == nil || IsNil(o.Plaintext) {
		return nil, false
	}
	return o.Plaintext, true
}

// HasPlaintext returns a boolean if a field has been set.
func (o *VariableVersion) HasPlaintext() bool {
	if o != nil && !IsNil(o.Plaintext) {
		return true
	}

	return false
}

// SetPlaintext gets a reference to the given string and assigns it to the Plaintext field.
func (o *VariableVersion) SetPlaintext(v string) {
	o.Plaintext = &v
}

func (o VariableVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Variable) {
		toSerialize["variable"] = o.Variable
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if o.Algo.IsSet() {
		toSerialize["algo"] = o.Algo.Get()
	}
	if o.KeyId.IsSet() {
		toSerialize["keyId"] = o.KeyId.Get()
	}
	if o.Nonce.IsSet() {
		toSerialize["nonce"] = o.Nonce.Get()
	}
	if o.Ciphertext.IsSet() {
		toSerialize["ciphertext"] = o.Ciphertext.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.CreatedBy.IsSet() {
		toSerialize["createdBy"] = o.CreatedBy.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Encrypted) {
		toSerialize["encrypted"] = o.Encrypted
	}
	if !IsNil(o.Plaintext) {
		toSerialize["plaintext"] = o.Plaintext
	}
	return toSerialize, nil
}

type NullableVariableVersion struct {
	value *VariableVersion
	isSet bool
}

func (v NullableVariableVersion) Get() *VariableVersion {
	return v.value
}

func (v *NullableVariableVersion) Set(val *VariableVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableVersion(val *VariableVersion) *NullableVariableVersion {
	return &NullableVariableVersion{value: val, isSet: true}
}

func (v NullableVariableVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


