/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the DeploymentAccessGate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentAccessGate{}

// DeploymentAccessGate List an application's per-deployment access-gate overrides.
type DeploymentAccessGate struct {
	Application *string `json:"application,omitempty"`
	Name *string `json:"name,omitempty"`
	AccessGate *string `json:"accessGate,omitempty"`
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
	AccessGateCredential NullableSealedSecret `json:"accessGateCredential,omitempty"`
}

// NewDeploymentAccessGate instantiates a new DeploymentAccessGate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentAccessGate() *DeploymentAccessGate {
	this := DeploymentAccessGate{}
	var accessGate string = "none"
	this.AccessGate = &accessGate
	return &this
}

// NewDeploymentAccessGateWithDefaults instantiates a new DeploymentAccessGate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentAccessGateWithDefaults() *DeploymentAccessGate {
	this := DeploymentAccessGate{}
	var accessGate string = "none"
	this.AccessGate = &accessGate
	return &this
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *DeploymentAccessGate) GetApplication() string {
	if o == nil || IsNil(o.Application) {
		var ret string
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAccessGate) GetApplicationOk() (*string, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given string and assigns it to the Application field.
func (o *DeploymentAccessGate) SetApplication(v string) {
	o.Application = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeploymentAccessGate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAccessGate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeploymentAccessGate) SetName(v string) {
	o.Name = &v
}

// GetAccessGate returns the AccessGate field value if set, zero value otherwise.
func (o *DeploymentAccessGate) GetAccessGate() string {
	if o == nil || IsNil(o.AccessGate) {
		var ret string
		return ret
	}
	return *o.AccessGate
}

// GetAccessGateOk returns a tuple with the AccessGate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAccessGate) GetAccessGateOk() (*string, bool) {
	if o == nil || IsNil(o.AccessGate) {
		return nil, false
	}
	return o.AccessGate, true
}

// HasAccessGate returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasAccessGate() bool {
	if o != nil && !IsNil(o.AccessGate) {
		return true
	}

	return false
}

// SetAccessGate gets a reference to the given string and assigns it to the AccessGate field.
func (o *DeploymentAccessGate) SetAccessGate(v string) {
	o.AccessGate = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeploymentAccessGate) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAccessGate) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeploymentAccessGate) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DeploymentAccessGate) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAccessGate) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DeploymentAccessGate) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentAccessGate) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentAccessGate) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *DeploymentAccessGate) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *DeploymentAccessGate) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *DeploymentAccessGate) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetAccessGateCredential returns the AccessGateCredential field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentAccessGate) GetAccessGateCredential() SealedSecret {
	if o == nil || IsNil(o.AccessGateCredential.Get()) {
		var ret SealedSecret
		return ret
	}
	return *o.AccessGateCredential.Get()
}

// GetAccessGateCredentialOk returns a tuple with the AccessGateCredential field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentAccessGate) GetAccessGateCredentialOk() (*SealedSecret, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessGateCredential.Get(), o.AccessGateCredential.IsSet()
}

// HasAccessGateCredential returns a boolean if a field has been set.
func (o *DeploymentAccessGate) HasAccessGateCredential() bool {
	if o != nil && o.AccessGateCredential.IsSet() {
		return true
	}

	return false
}

// SetAccessGateCredential gets a reference to the given NullableSealedSecret and assigns it to the AccessGateCredential field.
func (o *DeploymentAccessGate) SetAccessGateCredential(v SealedSecret) {
	o.AccessGateCredential.Set(&v)
}
// SetAccessGateCredentialNil sets the value for AccessGateCredential to be an explicit nil
func (o *DeploymentAccessGate) SetAccessGateCredentialNil() {
	o.AccessGateCredential.Set(nil)
}

// UnsetAccessGateCredential ensures that no value is present for AccessGateCredential, not even an explicit nil
func (o *DeploymentAccessGate) UnsetAccessGateCredential() {
	o.AccessGateCredential.Unset()
}

func (o DeploymentAccessGate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentAccessGate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AccessGate) {
		toSerialize["accessGate"] = o.AccessGate
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if o.AccessGateCredential.IsSet() {
		toSerialize["accessGateCredential"] = o.AccessGateCredential.Get()
	}
	return toSerialize, nil
}

type NullableDeploymentAccessGate struct {
	value *DeploymentAccessGate
	isSet bool
}

func (v NullableDeploymentAccessGate) Get() *DeploymentAccessGate {
	return v.value
}

func (v *NullableDeploymentAccessGate) Set(val *DeploymentAccessGate) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentAccessGate) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentAccessGate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentAccessGate(val *DeploymentAccessGate) *NullableDeploymentAccessGate {
	return &NullableDeploymentAccessGate{value: val, isSet: true}
}

func (v NullableDeploymentAccessGate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentAccessGate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


