/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the Machine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Machine{}

// Machine struct for Machine
type Machine struct {
	Instance *ProxmoxInstance `json:"instance,omitempty"`
	// The node within the instance — same string `app:proxmox:template` builds on.
	Node *string `json:"node,omitempty"`
	Vmid *int32 `json:"vmid,omitempty"`
	// How an operator addresses it; also the guest hostname the seed sets.
	Name *string `json:"name,omitempty"`
	Size *string `json:"size,omitempty"`
	// Disk as a block count, never gigabytes: a thin volume grows and never shrinks, so the invariant worth enforcing is \"this number only goes up\", and a count makes that checkable where a free-form size would not.
	DiskBlocks *int32 `json:"diskBlocks,omitempty"`
	// The template this was cloned from, by vmid. The reference count that decides when a superseded template may be deleted (§03): linked clones pin their base disk, and Proxmox will refuse — rightly — to delete a template that still has children.
	TemplateVmid *int32 `json:"templateVmid,omitempty"`
	// The island address chosen by the control plane's pool and registered with Proxmox, which is what dnsmasq then answers the machine's DHCP request with (docs/island-network.md — Proxmox's IPAM cannot allocate, so the platform still picks). Null until allocation; unique so the pool cannot double-allocate even if two provisions race.
	Address NullableString `json:"address,omitempty"`
	State *string `json:"state,omitempty"`
	// Why `Failed`, when it is. Carries the task's own words, never a paraphrase.
	Failure NullableString `json:"failure,omitempty"`
	// Which run through the flow this is, starting at 1 and incremented on every {@see self::reprovision()}. {@see \\App\\Entity\\ProvisioningLogLine} tags each captured line with the value that was current when it was written, so a retry's transcript starts fresh rather than appending to the failed attempt before it.
	ProvisionAttempt *int32 `json:"provisionAttempt,omitempty"`
	// When the current run through the flow began — set at construction and reset on every {@see self::reprovision()}, mirroring {@see ProxmoxInstance::$templateBuildStartedAt}. What {@see self::isProvisioningStale()} measures against: the real ceiling is the flow's own step deadlines ({@see \\App\\MessageHandler\\ProvisionMachineHandler}'s `BOOT_DEADLINE`/`TASK_DEADLINE`), and a run still going past {@see self::PROVISION_PRESUMED_DEAD_AFTER} is a worker that died holding it — a crash, an OOM, a deploy restart — rather than one still working.
	ProvisionStartedAt NullableTime `json:"provisionStartedAt,omitempty"`
	// The context this machine serves, if any. Nullable on purpose — see the class docblock.
	Swarm NullableString `json:"swarm,omitempty"`
	// The organization this machine was self-service-provisioned for, or null for one an operator made through `/admin/machines`. Nullable for the same reason `$swarm` is: an admin-made machine belongs to nobody's tenancy, and this column must not invent an owner for it. Set once, at creation, to the same organization that owns the paired `$swarm` — {@see Organization::markDeleted()} detaches it rather than deleting the row, matching how a BYO context's owner is handled.
	Organization NullableString `json:"organization,omitempty"`
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
	DiskGigabytes *int32 `json:"diskGigabytes,omitempty"`
	// Still mid-flow, and has been for longer than any healthy run takes — what {@see \\App\\MessageHandler\\SweepStaleMachineProvisionsHandler} sweeps for. A worker that crashed, OOM'd, or was recycled mid-step leaves the row exactly where it stood; nothing else ever revisits it, since the handler's own guard is \"state is Requested\" and every other step only ever moves the flow forward.
	ProvisioningStale *bool `json:"provisioningStale,omitempty"`
}

// NewMachine instantiates a new Machine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachine() *Machine {
	this := Machine{}
	var state string = "requested"
	this.State = &state
	return &this
}

// NewMachineWithDefaults instantiates a new Machine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineWithDefaults() *Machine {
	this := Machine{}
	var state string = "requested"
	this.State = &state
	return &this
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *Machine) GetInstance() ProxmoxInstance {
	if o == nil || IsNil(o.Instance) {
		var ret ProxmoxInstance
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetInstanceOk() (*ProxmoxInstance, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *Machine) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given ProxmoxInstance and assigns it to the Instance field.
func (o *Machine) SetInstance(v ProxmoxInstance) {
	o.Instance = &v
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *Machine) GetNode() string {
	if o == nil || IsNil(o.Node) {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetNodeOk() (*string, bool) {
	if o == nil || IsNil(o.Node) {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *Machine) HasNode() bool {
	if o != nil && !IsNil(o.Node) {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *Machine) SetNode(v string) {
	o.Node = &v
}

// GetVmid returns the Vmid field value if set, zero value otherwise.
func (o *Machine) GetVmid() int32 {
	if o == nil || IsNil(o.Vmid) {
		var ret int32
		return ret
	}
	return *o.Vmid
}

// GetVmidOk returns a tuple with the Vmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetVmidOk() (*int32, bool) {
	if o == nil || IsNil(o.Vmid) {
		return nil, false
	}
	return o.Vmid, true
}

// HasVmid returns a boolean if a field has been set.
func (o *Machine) HasVmid() bool {
	if o != nil && !IsNil(o.Vmid) {
		return true
	}

	return false
}

// SetVmid gets a reference to the given int32 and assigns it to the Vmid field.
func (o *Machine) SetVmid(v int32) {
	o.Vmid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Machine) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Machine) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Machine) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Machine) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Machine) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *Machine) SetSize(v string) {
	o.Size = &v
}

// GetDiskBlocks returns the DiskBlocks field value if set, zero value otherwise.
func (o *Machine) GetDiskBlocks() int32 {
	if o == nil || IsNil(o.DiskBlocks) {
		var ret int32
		return ret
	}
	return *o.DiskBlocks
}

// GetDiskBlocksOk returns a tuple with the DiskBlocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetDiskBlocksOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskBlocks) {
		return nil, false
	}
	return o.DiskBlocks, true
}

// HasDiskBlocks returns a boolean if a field has been set.
func (o *Machine) HasDiskBlocks() bool {
	if o != nil && !IsNil(o.DiskBlocks) {
		return true
	}

	return false
}

// SetDiskBlocks gets a reference to the given int32 and assigns it to the DiskBlocks field.
func (o *Machine) SetDiskBlocks(v int32) {
	o.DiskBlocks = &v
}

// GetTemplateVmid returns the TemplateVmid field value if set, zero value otherwise.
func (o *Machine) GetTemplateVmid() int32 {
	if o == nil || IsNil(o.TemplateVmid) {
		var ret int32
		return ret
	}
	return *o.TemplateVmid
}

// GetTemplateVmidOk returns a tuple with the TemplateVmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetTemplateVmidOk() (*int32, bool) {
	if o == nil || IsNil(o.TemplateVmid) {
		return nil, false
	}
	return o.TemplateVmid, true
}

// HasTemplateVmid returns a boolean if a field has been set.
func (o *Machine) HasTemplateVmid() bool {
	if o != nil && !IsNil(o.TemplateVmid) {
		return true
	}

	return false
}

// SetTemplateVmid gets a reference to the given int32 and assigns it to the TemplateVmid field.
func (o *Machine) SetTemplateVmid(v int32) {
	o.TemplateVmid = &v
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Machine) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Machine) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *Machine) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *Machine) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *Machine) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *Machine) UnsetAddress() {
	o.Address.Unset()
}

// GetState returns the State field value if set, zero value otherwise.
func (o *Machine) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *Machine) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *Machine) SetState(v string) {
	o.State = &v
}

// GetFailure returns the Failure field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Machine) GetFailure() string {
	if o == nil || IsNil(o.Failure.Get()) {
		var ret string
		return ret
	}
	return *o.Failure.Get()
}

// GetFailureOk returns a tuple with the Failure field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Machine) GetFailureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Failure.Get(), o.Failure.IsSet()
}

// HasFailure returns a boolean if a field has been set.
func (o *Machine) HasFailure() bool {
	if o != nil && o.Failure.IsSet() {
		return true
	}

	return false
}

// SetFailure gets a reference to the given NullableString and assigns it to the Failure field.
func (o *Machine) SetFailure(v string) {
	o.Failure.Set(&v)
}
// SetFailureNil sets the value for Failure to be an explicit nil
func (o *Machine) SetFailureNil() {
	o.Failure.Set(nil)
}

// UnsetFailure ensures that no value is present for Failure, not even an explicit nil
func (o *Machine) UnsetFailure() {
	o.Failure.Unset()
}

// GetProvisionAttempt returns the ProvisionAttempt field value if set, zero value otherwise.
func (o *Machine) GetProvisionAttempt() int32 {
	if o == nil || IsNil(o.ProvisionAttempt) {
		var ret int32
		return ret
	}
	return *o.ProvisionAttempt
}

// GetProvisionAttemptOk returns a tuple with the ProvisionAttempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetProvisionAttemptOk() (*int32, bool) {
	if o == nil || IsNil(o.ProvisionAttempt) {
		return nil, false
	}
	return o.ProvisionAttempt, true
}

// HasProvisionAttempt returns a boolean if a field has been set.
func (o *Machine) HasProvisionAttempt() bool {
	if o != nil && !IsNil(o.ProvisionAttempt) {
		return true
	}

	return false
}

// SetProvisionAttempt gets a reference to the given int32 and assigns it to the ProvisionAttempt field.
func (o *Machine) SetProvisionAttempt(v int32) {
	o.ProvisionAttempt = &v
}

// GetProvisionStartedAt returns the ProvisionStartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Machine) GetProvisionStartedAt() time.Time {
	if o == nil || IsNil(o.ProvisionStartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ProvisionStartedAt.Get()
}

// GetProvisionStartedAtOk returns a tuple with the ProvisionStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Machine) GetProvisionStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvisionStartedAt.Get(), o.ProvisionStartedAt.IsSet()
}

// HasProvisionStartedAt returns a boolean if a field has been set.
func (o *Machine) HasProvisionStartedAt() bool {
	if o != nil && o.ProvisionStartedAt.IsSet() {
		return true
	}

	return false
}

// SetProvisionStartedAt gets a reference to the given NullableTime and assigns it to the ProvisionStartedAt field.
func (o *Machine) SetProvisionStartedAt(v time.Time) {
	o.ProvisionStartedAt.Set(&v)
}
// SetProvisionStartedAtNil sets the value for ProvisionStartedAt to be an explicit nil
func (o *Machine) SetProvisionStartedAtNil() {
	o.ProvisionStartedAt.Set(nil)
}

// UnsetProvisionStartedAt ensures that no value is present for ProvisionStartedAt, not even an explicit nil
func (o *Machine) UnsetProvisionStartedAt() {
	o.ProvisionStartedAt.Unset()
}

// GetSwarm returns the Swarm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Machine) GetSwarm() string {
	if o == nil || IsNil(o.Swarm.Get()) {
		var ret string
		return ret
	}
	return *o.Swarm.Get()
}

// GetSwarmOk returns a tuple with the Swarm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Machine) GetSwarmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Swarm.Get(), o.Swarm.IsSet()
}

// HasSwarm returns a boolean if a field has been set.
func (o *Machine) HasSwarm() bool {
	if o != nil && o.Swarm.IsSet() {
		return true
	}

	return false
}

// SetSwarm gets a reference to the given NullableString and assigns it to the Swarm field.
func (o *Machine) SetSwarm(v string) {
	o.Swarm.Set(&v)
}
// SetSwarmNil sets the value for Swarm to be an explicit nil
func (o *Machine) SetSwarmNil() {
	o.Swarm.Set(nil)
}

// UnsetSwarm ensures that no value is present for Swarm, not even an explicit nil
func (o *Machine) UnsetSwarm() {
	o.Swarm.Unset()
}

// GetOrganization returns the Organization field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Machine) GetOrganization() string {
	if o == nil || IsNil(o.Organization.Get()) {
		var ret string
		return ret
	}
	return *o.Organization.Get()
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Machine) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Organization.Get(), o.Organization.IsSet()
}

// HasOrganization returns a boolean if a field has been set.
func (o *Machine) HasOrganization() bool {
	if o != nil && o.Organization.IsSet() {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given NullableString and assigns it to the Organization field.
func (o *Machine) SetOrganization(v string) {
	o.Organization.Set(&v)
}
// SetOrganizationNil sets the value for Organization to be an explicit nil
func (o *Machine) SetOrganizationNil() {
	o.Organization.Set(nil)
}

// UnsetOrganization ensures that no value is present for Organization, not even an explicit nil
func (o *Machine) UnsetOrganization() {
	o.Organization.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Machine) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Machine) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Machine) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Machine) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Machine) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Machine) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Machine) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Machine) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Machine) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *Machine) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *Machine) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *Machine) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetDiskGigabytes returns the DiskGigabytes field value if set, zero value otherwise.
func (o *Machine) GetDiskGigabytes() int32 {
	if o == nil || IsNil(o.DiskGigabytes) {
		var ret int32
		return ret
	}
	return *o.DiskGigabytes
}

// GetDiskGigabytesOk returns a tuple with the DiskGigabytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetDiskGigabytesOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskGigabytes) {
		return nil, false
	}
	return o.DiskGigabytes, true
}

// HasDiskGigabytes returns a boolean if a field has been set.
func (o *Machine) HasDiskGigabytes() bool {
	if o != nil && !IsNil(o.DiskGigabytes) {
		return true
	}

	return false
}

// SetDiskGigabytes gets a reference to the given int32 and assigns it to the DiskGigabytes field.
func (o *Machine) SetDiskGigabytes(v int32) {
	o.DiskGigabytes = &v
}

// GetProvisioningStale returns the ProvisioningStale field value if set, zero value otherwise.
func (o *Machine) GetProvisioningStale() bool {
	if o == nil || IsNil(o.ProvisioningStale) {
		var ret bool
		return ret
	}
	return *o.ProvisioningStale
}

// GetProvisioningStaleOk returns a tuple with the ProvisioningStale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Machine) GetProvisioningStaleOk() (*bool, bool) {
	if o == nil || IsNil(o.ProvisioningStale) {
		return nil, false
	}
	return o.ProvisioningStale, true
}

// HasProvisioningStale returns a boolean if a field has been set.
func (o *Machine) HasProvisioningStale() bool {
	if o != nil && !IsNil(o.ProvisioningStale) {
		return true
	}

	return false
}

// SetProvisioningStale gets a reference to the given bool and assigns it to the ProvisioningStale field.
func (o *Machine) SetProvisioningStale(v bool) {
	o.ProvisioningStale = &v
}

func (o Machine) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Machine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Node) {
		toSerialize["node"] = o.Node
	}
	if !IsNil(o.Vmid) {
		toSerialize["vmid"] = o.Vmid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.DiskBlocks) {
		toSerialize["diskBlocks"] = o.DiskBlocks
	}
	if !IsNil(o.TemplateVmid) {
		toSerialize["templateVmid"] = o.TemplateVmid
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if o.Failure.IsSet() {
		toSerialize["failure"] = o.Failure.Get()
	}
	if !IsNil(o.ProvisionAttempt) {
		toSerialize["provisionAttempt"] = o.ProvisionAttempt
	}
	if o.ProvisionStartedAt.IsSet() {
		toSerialize["provisionStartedAt"] = o.ProvisionStartedAt.Get()
	}
	if o.Swarm.IsSet() {
		toSerialize["swarm"] = o.Swarm.Get()
	}
	if o.Organization.IsSet() {
		toSerialize["organization"] = o.Organization.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if !IsNil(o.DiskGigabytes) {
		toSerialize["diskGigabytes"] = o.DiskGigabytes
	}
	if !IsNil(o.ProvisioningStale) {
		toSerialize["provisioningStale"] = o.ProvisioningStale
	}
	return toSerialize, nil
}

type NullableMachine struct {
	value *Machine
	isSet bool
}

func (v NullableMachine) Get() *Machine {
	return v.value
}

func (v *NullableMachine) Set(val *Machine) {
	v.value = val
	v.isSet = true
}

func (v NullableMachine) IsSet() bool {
	return v.isSet
}

func (v *NullableMachine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachine(val *Machine) *NullableMachine {
	return &NullableMachine{value: val, isSet: true}
}

func (v NullableMachine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


