/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"fmt"
)


// ServiceCpuLimit Nanoseconds of CPU (compose deploy.resources.limits.cpus), null = unset.
type ServiceCpuLimit struct {
	Int32 *int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ServiceCpuLimit) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ServiceCpuLimit)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ServiceCpuLimit) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableServiceCpuLimit struct {
	value *ServiceCpuLimit
	isSet bool
}

func (v NullableServiceCpuLimit) Get() *ServiceCpuLimit {
	return v.value
}

func (v *NullableServiceCpuLimit) Set(val *ServiceCpuLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCpuLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCpuLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCpuLimit(val *ServiceCpuLimit) *NullableServiceCpuLimit {
	return &NullableServiceCpuLimit{value: val, isSet: true}
}

func (v NullableServiceCpuLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCpuLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


