/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagedServiceManagedServiceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServiceManagedServiceInput{}

// ManagedServiceManagedServiceInput One tenant's database or bucket on a shared engine.  **Owned by an organization and bound to applications** — not a per-application toggle. The distinction is the whole reason this entity exists in this shape: a toggle with a unique foreign key cannot express one database backing both a web app and its worker, and cannot survive an application being rebuilt under a new name. Binding is therefore explicit ({@see ServiceBinding}), which costs one step at creation and buys sharing, one billing shape, one permission model and one set of verbs across databases *and* buckets.  A bucket is the same noun with a different {@see $kind}. Only the driver that executes the tenancy operations differs.  Soft-deleted, so a destroy is recoverable within its grace period ({@see ManagedServiceRepository::GRACE_PERIOD}); only the driver's `DROP` is not, and that runs on the far side of it.  **Read is scoped by membership and writing by role**, which are different questions: {@see \\App\\ApiResource\\ManagedServiceOwnerExtension} filters the query, so another tenant's id answers 404 rather than confirming it exists, while {@see \\App\\Security\\Voter\\ManageVoter} governs the verbs inside each processor — a plain member may see their organization's databases without being able to destroy one.  Delete does *not* fall through to the generic soft-delete processor: dropping a database is not stamping a column, and the difference is a tenant's data. See {@see \\App\\State\\ManagedServiceDestroyProcessor}.
type ManagedServiceManagedServiceInput struct {
	// The engine, as the catalogue names it — `postgres:17`, `mysql:8.0`.
	Engine string `json:"engine" validate:"regexp=^([a-z]+:[0-9]+(\\\\.[0-9]+)?)$"`
	// The tenant's own name for it — what appears in the UI and in `sc service ls`.
	Slug string `json:"slug" validate:"regexp=^([a-z0-9][a-z0-9-]*)$"`
	Organization NullableString `json:"organization"`
}

type _ManagedServiceManagedServiceInput ManagedServiceManagedServiceInput

// NewManagedServiceManagedServiceInput instantiates a new ManagedServiceManagedServiceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServiceManagedServiceInput(engine string, slug string, organization NullableString) *ManagedServiceManagedServiceInput {
	this := ManagedServiceManagedServiceInput{}
	this.Engine = engine
	this.Slug = slug
	this.Organization = organization
	return &this
}

// NewManagedServiceManagedServiceInputWithDefaults instantiates a new ManagedServiceManagedServiceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServiceManagedServiceInputWithDefaults() *ManagedServiceManagedServiceInput {
	this := ManagedServiceManagedServiceInput{}
	var engine string = ""
	this.Engine = engine
	var slug string = ""
	this.Slug = slug
	return &this
}

// GetEngine returns the Engine field value
func (o *ManagedServiceManagedServiceInput) GetEngine() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engine
}

// GetEngineOk returns a tuple with the Engine field value
// and a boolean to check if the value has been set.
func (o *ManagedServiceManagedServiceInput) GetEngineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engine, true
}

// SetEngine sets field value
func (o *ManagedServiceManagedServiceInput) SetEngine(v string) {
	o.Engine = v
}

// GetSlug returns the Slug field value
func (o *ManagedServiceManagedServiceInput) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ManagedServiceManagedServiceInput) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ManagedServiceManagedServiceInput) SetSlug(v string) {
	o.Slug = v
}

// GetOrganization returns the Organization field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ManagedServiceManagedServiceInput) GetOrganization() string {
	if o == nil || o.Organization.Get() == nil {
		var ret string
		return ret
	}

	return *o.Organization.Get()
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ManagedServiceManagedServiceInput) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Organization.Get(), o.Organization.IsSet()
}

// SetOrganization sets field value
func (o *ManagedServiceManagedServiceInput) SetOrganization(v string) {
	o.Organization.Set(&v)
}

func (o ManagedServiceManagedServiceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServiceManagedServiceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engine"] = o.Engine
	toSerialize["slug"] = o.Slug
	toSerialize["organization"] = o.Organization.Get()
	return toSerialize, nil
}

func (o *ManagedServiceManagedServiceInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engine",
		"slug",
		"organization",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServiceManagedServiceInput := _ManagedServiceManagedServiceInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServiceManagedServiceInput)

	if err != nil {
		return err
	}

	*o = ManagedServiceManagedServiceInput(varManagedServiceManagedServiceInput)

	return err
}

type NullableManagedServiceManagedServiceInput struct {
	value *ManagedServiceManagedServiceInput
	isSet bool
}

func (v NullableManagedServiceManagedServiceInput) Get() *ManagedServiceManagedServiceInput {
	return v.value
}

func (v *NullableManagedServiceManagedServiceInput) Set(val *ManagedServiceManagedServiceInput) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServiceManagedServiceInput) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServiceManagedServiceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServiceManagedServiceInput(val *ManagedServiceManagedServiceInput) *NullableManagedServiceManagedServiceInput {
	return &NullableManagedServiceManagedServiceInput{value: val, isSet: true}
}

func (v NullableManagedServiceManagedServiceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServiceManagedServiceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


