/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
)

// checks if the ConstraintViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConstraintViolation{}

// ConstraintViolation Unprocessable entity
type ConstraintViolation struct {
	Status *int32 `json:"status,omitempty"`
	Violations []ConstraintViolationViolationsInner `json:"violations,omitempty"`
	Detail *string `json:"detail,omitempty"`
	Type *string `json:"type,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Instance NullableString `json:"instance,omitempty"`
}

// NewConstraintViolation instantiates a new ConstraintViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConstraintViolation() *ConstraintViolation {
	this := ConstraintViolation{}
	var status int32 = 422
	this.Status = &status
	return &this
}

// NewConstraintViolationWithDefaults instantiates a new ConstraintViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConstraintViolationWithDefaults() *ConstraintViolation {
	this := ConstraintViolation{}
	var status int32 = 422
	this.Status = &status
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ConstraintViolation) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstraintViolation) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ConstraintViolation) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ConstraintViolation) SetStatus(v int32) {
	o.Status = &v
}

// GetViolations returns the Violations field value if set, zero value otherwise.
func (o *ConstraintViolation) GetViolations() []ConstraintViolationViolationsInner {
	if o == nil || IsNil(o.Violations) {
		var ret []ConstraintViolationViolationsInner
		return ret
	}
	return o.Violations
}

// GetViolationsOk returns a tuple with the Violations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstraintViolation) GetViolationsOk() ([]ConstraintViolationViolationsInner, bool) {
	if o == nil || IsNil(o.Violations) {
		return nil, false
	}
	return o.Violations, true
}

// HasViolations returns a boolean if a field has been set.
func (o *ConstraintViolation) HasViolations() bool {
	if o != nil && !IsNil(o.Violations) {
		return true
	}

	return false
}

// SetViolations gets a reference to the given []ConstraintViolationViolationsInner and assigns it to the Violations field.
func (o *ConstraintViolation) SetViolations(v []ConstraintViolationViolationsInner) {
	o.Violations = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ConstraintViolation) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstraintViolation) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ConstraintViolation) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ConstraintViolation) SetDetail(v string) {
	o.Detail = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConstraintViolation) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstraintViolation) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConstraintViolation) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ConstraintViolation) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConstraintViolation) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConstraintViolation) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ConstraintViolation) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ConstraintViolation) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *ConstraintViolation) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ConstraintViolation) UnsetTitle() {
	o.Title.Unset()
}

// GetInstance returns the Instance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConstraintViolation) GetInstance() string {
	if o == nil || IsNil(o.Instance.Get()) {
		var ret string
		return ret
	}
	return *o.Instance.Get()
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConstraintViolation) GetInstanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instance.Get(), o.Instance.IsSet()
}

// HasInstance returns a boolean if a field has been set.
func (o *ConstraintViolation) HasInstance() bool {
	if o != nil && o.Instance.IsSet() {
		return true
	}

	return false
}

// SetInstance gets a reference to the given NullableString and assigns it to the Instance field.
func (o *ConstraintViolation) SetInstance(v string) {
	o.Instance.Set(&v)
}
// SetInstanceNil sets the value for Instance to be an explicit nil
func (o *ConstraintViolation) SetInstanceNil() {
	o.Instance.Set(nil)
}

// UnsetInstance ensures that no value is present for Instance, not even an explicit nil
func (o *ConstraintViolation) UnsetInstance() {
	o.Instance.Unset()
}

func (o ConstraintViolation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConstraintViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Violations) {
		toSerialize["violations"] = o.Violations
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Instance.IsSet() {
		toSerialize["instance"] = o.Instance.Get()
	}
	return toSerialize, nil
}

type NullableConstraintViolation struct {
	value *ConstraintViolation
	isSet bool
}

func (v NullableConstraintViolation) Get() *ConstraintViolation {
	return v.value
}

func (v *NullableConstraintViolation) Set(val *ConstraintViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableConstraintViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableConstraintViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConstraintViolation(val *ConstraintViolation) *NullableConstraintViolation {
	return &NullableConstraintViolation{value: val, isSet: true}
}

func (v NullableConstraintViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConstraintViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


