/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdoptionApprovalAdoptionApprovalInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdoptionApprovalAdoptionApprovalInput{}

// AdoptionApprovalAdoptionApprovalInput A human's decision on one compose service the adoption planner detected — approve it, or decline it (§15).  **The switch arms detection; this is what authorizes the act.** {@see \\App\\Service\\ManagedService\\Adoption\\AdoptionReconciler} only ever turns a candidate into a real {@see ManagedService}/{@see ServiceBinding} pair when a row here says `approved`, and only for the compose service name recorded — a rename is a different candidate with no decision of its own yet.  **There is no \"pending\" row.** A service the planner reports and nobody has decided on simply has none here; recording one for every candidate on every deploy would need cleaning up the moment a service is renamed away, for a state (\"undecided\") a missing row already expresses for free.  One row per (application, compose service): deciding again — approving after a rejection, or the reverse — updates it rather than accumulating history, because only the current decision governs what the next deploy does.
type AdoptionApprovalAdoptionApprovalInput struct {
	Application NullableString `json:"application"`
	ComposeServiceName string `json:"composeServiceName"`
	Approved *bool `json:"approved,omitempty"`
}

type _AdoptionApprovalAdoptionApprovalInput AdoptionApprovalAdoptionApprovalInput

// NewAdoptionApprovalAdoptionApprovalInput instantiates a new AdoptionApprovalAdoptionApprovalInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdoptionApprovalAdoptionApprovalInput(application NullableString, composeServiceName string) *AdoptionApprovalAdoptionApprovalInput {
	this := AdoptionApprovalAdoptionApprovalInput{}
	this.Application = application
	this.ComposeServiceName = composeServiceName
	var approved bool = false
	this.Approved = &approved
	return &this
}

// NewAdoptionApprovalAdoptionApprovalInputWithDefaults instantiates a new AdoptionApprovalAdoptionApprovalInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdoptionApprovalAdoptionApprovalInputWithDefaults() *AdoptionApprovalAdoptionApprovalInput {
	this := AdoptionApprovalAdoptionApprovalInput{}
	var composeServiceName string = ""
	this.ComposeServiceName = composeServiceName
	var approved bool = false
	this.Approved = &approved
	return &this
}

// GetApplication returns the Application field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AdoptionApprovalAdoptionApprovalInput) GetApplication() string {
	if o == nil || o.Application.Get() == nil {
		var ret string
		return ret
	}

	return *o.Application.Get()
}

// GetApplicationOk returns a tuple with the Application field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AdoptionApprovalAdoptionApprovalInput) GetApplicationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Application.Get(), o.Application.IsSet()
}

// SetApplication sets field value
func (o *AdoptionApprovalAdoptionApprovalInput) SetApplication(v string) {
	o.Application.Set(&v)
}

// GetComposeServiceName returns the ComposeServiceName field value
func (o *AdoptionApprovalAdoptionApprovalInput) GetComposeServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComposeServiceName
}

// GetComposeServiceNameOk returns a tuple with the ComposeServiceName field value
// and a boolean to check if the value has been set.
func (o *AdoptionApprovalAdoptionApprovalInput) GetComposeServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComposeServiceName, true
}

// SetComposeServiceName sets field value
func (o *AdoptionApprovalAdoptionApprovalInput) SetComposeServiceName(v string) {
	o.ComposeServiceName = v
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *AdoptionApprovalAdoptionApprovalInput) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptionApprovalAdoptionApprovalInput) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *AdoptionApprovalAdoptionApprovalInput) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *AdoptionApprovalAdoptionApprovalInput) SetApproved(v bool) {
	o.Approved = &v
}

func (o AdoptionApprovalAdoptionApprovalInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdoptionApprovalAdoptionApprovalInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application"] = o.Application.Get()
	toSerialize["composeServiceName"] = o.ComposeServiceName
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	return toSerialize, nil
}

func (o *AdoptionApprovalAdoptionApprovalInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application",
		"composeServiceName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdoptionApprovalAdoptionApprovalInput := _AdoptionApprovalAdoptionApprovalInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdoptionApprovalAdoptionApprovalInput)

	if err != nil {
		return err
	}

	*o = AdoptionApprovalAdoptionApprovalInput(varAdoptionApprovalAdoptionApprovalInput)

	return err
}

type NullableAdoptionApprovalAdoptionApprovalInput struct {
	value *AdoptionApprovalAdoptionApprovalInput
	isSet bool
}

func (v NullableAdoptionApprovalAdoptionApprovalInput) Get() *AdoptionApprovalAdoptionApprovalInput {
	return v.value
}

func (v *NullableAdoptionApprovalAdoptionApprovalInput) Set(val *AdoptionApprovalAdoptionApprovalInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAdoptionApprovalAdoptionApprovalInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAdoptionApprovalAdoptionApprovalInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdoptionApprovalAdoptionApprovalInput(val *AdoptionApprovalAdoptionApprovalInput) *NullableAdoptionApprovalAdoptionApprovalInput {
	return &NullableAdoptionApprovalAdoptionApprovalInput{value: val, isSet: true}
}

func (v NullableAdoptionApprovalAdoptionApprovalInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdoptionApprovalAdoptionApprovalInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


