/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"fmt"
)


// CreditTransactionUsageBytes The byte snapshot a storage debit was computed from — the evidence a GiB-month charge can be checked against, the same role {@see $usageSeconds} plays for a compute debit. Null on anything but a storage debit.
type CreditTransactionUsageBytes struct {
	Int32 *int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CreditTransactionUsageBytes) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CreditTransactionUsageBytes)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreditTransactionUsageBytes) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableCreditTransactionUsageBytes struct {
	value *CreditTransactionUsageBytes
	isSet bool
}

func (v NullableCreditTransactionUsageBytes) Get() *CreditTransactionUsageBytes {
	return v.value
}

func (v *NullableCreditTransactionUsageBytes) Set(val *CreditTransactionUsageBytes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditTransactionUsageBytes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditTransactionUsageBytes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditTransactionUsageBytes(val *CreditTransactionUsageBytes) *NullableCreditTransactionUsageBytes {
	return &NullableCreditTransactionUsageBytes{value: val, isSet: true}
}

func (v NullableCreditTransactionUsageBytes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditTransactionUsageBytes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


