/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BundleContextInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BundleContextInput{}

// BundleContextInput struct for BundleContextInput
type BundleContextInput struct {
	Service string `json:"service"`
	ContextSha256 string `json:"contextSha256" validate:"regexp=^([a-f0-9]{64})$"`
	Dockerfile *string `json:"dockerfile,omitempty"`
	AdditionalContexts []BundleAdditionalContextInput `json:"additionalContexts,omitempty"`
}

type _BundleContextInput BundleContextInput

// NewBundleContextInput instantiates a new BundleContextInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBundleContextInput(service string, contextSha256 string) *BundleContextInput {
	this := BundleContextInput{}
	this.Service = service
	this.ContextSha256 = contextSha256
	var dockerfile string = "Dockerfile"
	this.Dockerfile = &dockerfile
	return &this
}

// NewBundleContextInputWithDefaults instantiates a new BundleContextInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBundleContextInputWithDefaults() *BundleContextInput {
	this := BundleContextInput{}
	var service string = ""
	this.Service = service
	var contextSha256 string = ""
	this.ContextSha256 = contextSha256
	var dockerfile string = "Dockerfile"
	this.Dockerfile = &dockerfile
	return &this
}

// GetService returns the Service field value
func (o *BundleContextInput) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *BundleContextInput) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *BundleContextInput) SetService(v string) {
	o.Service = v
}

// GetContextSha256 returns the ContextSha256 field value
func (o *BundleContextInput) GetContextSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContextSha256
}

// GetContextSha256Ok returns a tuple with the ContextSha256 field value
// and a boolean to check if the value has been set.
func (o *BundleContextInput) GetContextSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextSha256, true
}

// SetContextSha256 sets field value
func (o *BundleContextInput) SetContextSha256(v string) {
	o.ContextSha256 = v
}

// GetDockerfile returns the Dockerfile field value if set, zero value otherwise.
func (o *BundleContextInput) GetDockerfile() string {
	if o == nil || IsNil(o.Dockerfile) {
		var ret string
		return ret
	}
	return *o.Dockerfile
}

// GetDockerfileOk returns a tuple with the Dockerfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BundleContextInput) GetDockerfileOk() (*string, bool) {
	if o == nil || IsNil(o.Dockerfile) {
		return nil, false
	}
	return o.Dockerfile, true
}

// HasDockerfile returns a boolean if a field has been set.
func (o *BundleContextInput) HasDockerfile() bool {
	if o != nil && !IsNil(o.Dockerfile) {
		return true
	}

	return false
}

// SetDockerfile gets a reference to the given string and assigns it to the Dockerfile field.
func (o *BundleContextInput) SetDockerfile(v string) {
	o.Dockerfile = &v
}

// GetAdditionalContexts returns the AdditionalContexts field value if set, zero value otherwise.
func (o *BundleContextInput) GetAdditionalContexts() []BundleAdditionalContextInput {
	if o == nil || IsNil(o.AdditionalContexts) {
		var ret []BundleAdditionalContextInput
		return ret
	}
	return o.AdditionalContexts
}

// GetAdditionalContextsOk returns a tuple with the AdditionalContexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BundleContextInput) GetAdditionalContextsOk() ([]BundleAdditionalContextInput, bool) {
	if o == nil || IsNil(o.AdditionalContexts) {
		return nil, false
	}
	return o.AdditionalContexts, true
}

// HasAdditionalContexts returns a boolean if a field has been set.
func (o *BundleContextInput) HasAdditionalContexts() bool {
	if o != nil && !IsNil(o.AdditionalContexts) {
		return true
	}

	return false
}

// SetAdditionalContexts gets a reference to the given []BundleAdditionalContextInput and assigns it to the AdditionalContexts field.
func (o *BundleContextInput) SetAdditionalContexts(v []BundleAdditionalContextInput) {
	o.AdditionalContexts = v
}

func (o BundleContextInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BundleContextInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service"] = o.Service
	toSerialize["contextSha256"] = o.ContextSha256
	if !IsNil(o.Dockerfile) {
		toSerialize["dockerfile"] = o.Dockerfile
	}
	if !IsNil(o.AdditionalContexts) {
		toSerialize["additionalContexts"] = o.AdditionalContexts
	}
	return toSerialize, nil
}

func (o *BundleContextInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service",
		"contextSha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBundleContextInput := _BundleContextInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBundleContextInput)

	if err != nil {
		return err
	}

	*o = BundleContextInput(varBundleContextInput)

	return err
}

type NullableBundleContextInput struct {
	value *BundleContextInput
	isSet bool
}

func (v NullableBundleContextInput) Get() *BundleContextInput {
	return v.value
}

func (v *NullableBundleContextInput) Set(val *BundleContextInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleContextInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleContextInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleContextInput(val *BundleContextInput) *NullableBundleContextInput {
	return &NullableBundleContextInput{value: val, isSet: true}
}

func (v NullableBundleContextInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleContextInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


