/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the DeploymentBundleUploadDeclareOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentBundleUploadDeclareOutput{}

// DeploymentBundleUploadDeclareOutput An IMMUTABLE compose revision. A deploy is a new row; rollback re-points Application::$currentDeployment at an older one. Placement is resolved onto this row (targetSwarm) at deploy time, so migration is just the next revision.
type DeploymentBundleUploadDeclareOutput struct {
	Contexts []BundleUploadTarget `json:"contexts,omitempty"`
	AdditionalContexts []BundleUploadTarget `json:"additionalContexts,omitempty"`
	Images []BundleUploadTarget `json:"images,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// NewDeploymentBundleUploadDeclareOutput instantiates a new DeploymentBundleUploadDeclareOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentBundleUploadDeclareOutput() *DeploymentBundleUploadDeclareOutput {
	this := DeploymentBundleUploadDeclareOutput{}
	return &this
}

// NewDeploymentBundleUploadDeclareOutputWithDefaults instantiates a new DeploymentBundleUploadDeclareOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentBundleUploadDeclareOutputWithDefaults() *DeploymentBundleUploadDeclareOutput {
	this := DeploymentBundleUploadDeclareOutput{}
	return &this
}

// GetContexts returns the Contexts field value if set, zero value otherwise.
func (o *DeploymentBundleUploadDeclareOutput) GetContexts() []BundleUploadTarget {
	if o == nil || IsNil(o.Contexts) {
		var ret []BundleUploadTarget
		return ret
	}
	return o.Contexts
}

// GetContextsOk returns a tuple with the Contexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadDeclareOutput) GetContextsOk() ([]BundleUploadTarget, bool) {
	if o == nil || IsNil(o.Contexts) {
		return nil, false
	}
	return o.Contexts, true
}

// HasContexts returns a boolean if a field has been set.
func (o *DeploymentBundleUploadDeclareOutput) HasContexts() bool {
	if o != nil && !IsNil(o.Contexts) {
		return true
	}

	return false
}

// SetContexts gets a reference to the given []BundleUploadTarget and assigns it to the Contexts field.
func (o *DeploymentBundleUploadDeclareOutput) SetContexts(v []BundleUploadTarget) {
	o.Contexts = v
}

// GetAdditionalContexts returns the AdditionalContexts field value if set, zero value otherwise.
func (o *DeploymentBundleUploadDeclareOutput) GetAdditionalContexts() []BundleUploadTarget {
	if o == nil || IsNil(o.AdditionalContexts) {
		var ret []BundleUploadTarget
		return ret
	}
	return o.AdditionalContexts
}

// GetAdditionalContextsOk returns a tuple with the AdditionalContexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadDeclareOutput) GetAdditionalContextsOk() ([]BundleUploadTarget, bool) {
	if o == nil || IsNil(o.AdditionalContexts) {
		return nil, false
	}
	return o.AdditionalContexts, true
}

// HasAdditionalContexts returns a boolean if a field has been set.
func (o *DeploymentBundleUploadDeclareOutput) HasAdditionalContexts() bool {
	if o != nil && !IsNil(o.AdditionalContexts) {
		return true
	}

	return false
}

// SetAdditionalContexts gets a reference to the given []BundleUploadTarget and assigns it to the AdditionalContexts field.
func (o *DeploymentBundleUploadDeclareOutput) SetAdditionalContexts(v []BundleUploadTarget) {
	o.AdditionalContexts = v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *DeploymentBundleUploadDeclareOutput) GetImages() []BundleUploadTarget {
	if o == nil || IsNil(o.Images) {
		var ret []BundleUploadTarget
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadDeclareOutput) GetImagesOk() ([]BundleUploadTarget, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *DeploymentBundleUploadDeclareOutput) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []BundleUploadTarget and assigns it to the Images field.
func (o *DeploymentBundleUploadDeclareOutput) SetImages(v []BundleUploadTarget) {
	o.Images = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *DeploymentBundleUploadDeclareOutput) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadDeclareOutput) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *DeploymentBundleUploadDeclareOutput) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *DeploymentBundleUploadDeclareOutput) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o DeploymentBundleUploadDeclareOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentBundleUploadDeclareOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contexts) {
		toSerialize["contexts"] = o.Contexts
	}
	if !IsNil(o.AdditionalContexts) {
		toSerialize["additionalContexts"] = o.AdditionalContexts
	}
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableDeploymentBundleUploadDeclareOutput struct {
	value *DeploymentBundleUploadDeclareOutput
	isSet bool
}

func (v NullableDeploymentBundleUploadDeclareOutput) Get() *DeploymentBundleUploadDeclareOutput {
	return v.value
}

func (v *NullableDeploymentBundleUploadDeclareOutput) Set(val *DeploymentBundleUploadDeclareOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentBundleUploadDeclareOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentBundleUploadDeclareOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentBundleUploadDeclareOutput(val *DeploymentBundleUploadDeclareOutput) *NullableDeploymentBundleUploadDeclareOutput {
	return &NullableDeploymentBundleUploadDeclareOutput{value: val, isSet: true}
}

func (v NullableDeploymentBundleUploadDeclareOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentBundleUploadDeclareOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


