/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the OrganizationJsonMergePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationJsonMergePatch{}

// OrganizationJsonMergePatch Ownership and (future) billing boundary. Owns applications, may own BYO swarms.
type OrganizationJsonMergePatch struct {
	MachineAccount NullableUser `json:"machineAccount,omitempty"`
	Name *string `json:"name,omitempty"`
	// `unique: true` stops two organizations holding the same *string*; the constraint stops two holding strings that fold to the same **stack name**, which the database has no way to express (#860). Both are needed: the column guards the identifier, the constraint guards what is derived from it.
	Slug *string `json:"slug,omitempty"`
	// The skin this organization's members see, or null to take the instance's.
	Theme NullableString `json:"theme,omitempty"`
	// An operator's grant of a tier this organization would not reach through any member — {@see \\App\\Enum\\AccountTier::Verified} in particular, which is granted rather than earned and belongs to a contractual relationship with the *organization*, not incidentally to whichever of its members happens to carry the highest personal tier ({@see \\App\\Service\\Trust\\TierResolver::forOrganization()}). A member individually pinned `Verified` still lifts the org the same way a `Trusted` member always has — this pin is for granting it to the org directly, without needing a person to hang it on.
	TierPin NullableString `json:"tierPin,omitempty"`
	TierPinnedAt NullableTime `json:"tierPinnedAt,omitempty"`
	TierPinnedBy NullableUser `json:"tierPinnedBy,omitempty"`
	TierPinReason NullableString `json:"tierPinReason,omitempty"`
	// When {@see \\App\\MessageHandler\\CheckRunwayHandler} last warned this organization that its projected runway had dropped below the threshold; null once no warning is outstanding. Set once per crossing and cleared the moment the projection recovers — by a top-up or by the burn easing off — which is what makes \"warn once, re-arm on recovery\" a fact this column can answer rather than something re-derived from the notification table on every tick.
	LowBalanceWarnedAt NullableTime `json:"lowBalanceWarnedAt,omitempty"`
	// When an Owner/Admin turned on the requirement that every member of this organization protects their account with a second factor; null means it is optional. A reversible policy toggle, stamped like {@see User::$disabledAt} rather than a verdict, so no \"who set it\" attribution.
	TwoFactorRequiredAt NullableTime `json:"twoFactorRequiredAt,omitempty"`
	Memberships []Membership `json:"memberships,omitempty"`
	Applications []string `json:"applications,omitempty"`
	// BYO swarms owned by this organization.
	Swarms []string `json:"swarms,omitempty"`
	Machines []Machine `json:"machines,omitempty"`
	// The append-only credit ledger.
	CreditTransactions []string `json:"creditTransactions,omitempty"`
	Variables []Variable `json:"variables,omitempty"`
	Signals []OrganizationSignal `json:"signals,omitempty"`
	Id *string `json:"id,omitempty"`
	DeletedAt NullableTime `json:"deletedAt,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
	TierPinned *bool `json:"tierPinned,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
}

// NewOrganizationJsonMergePatch instantiates a new OrganizationJsonMergePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationJsonMergePatch() *OrganizationJsonMergePatch {
	this := OrganizationJsonMergePatch{}
	return &this
}

// NewOrganizationJsonMergePatchWithDefaults instantiates a new OrganizationJsonMergePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationJsonMergePatchWithDefaults() *OrganizationJsonMergePatch {
	this := OrganizationJsonMergePatch{}
	return &this
}

// GetMachineAccount returns the MachineAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetMachineAccount() User {
	if o == nil || IsNil(o.MachineAccount.Get()) {
		var ret User
		return ret
	}
	return *o.MachineAccount.Get()
}

// GetMachineAccountOk returns a tuple with the MachineAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetMachineAccountOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineAccount.Get(), o.MachineAccount.IsSet()
}

// HasMachineAccount returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasMachineAccount() bool {
	if o != nil && o.MachineAccount.IsSet() {
		return true
	}

	return false
}

// SetMachineAccount gets a reference to the given NullableUser and assigns it to the MachineAccount field.
func (o *OrganizationJsonMergePatch) SetMachineAccount(v User) {
	o.MachineAccount.Set(&v)
}
// SetMachineAccountNil sets the value for MachineAccount to be an explicit nil
func (o *OrganizationJsonMergePatch) SetMachineAccountNil() {
	o.MachineAccount.Set(nil)
}

// UnsetMachineAccount ensures that no value is present for MachineAccount, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetMachineAccount() {
	o.MachineAccount.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationJsonMergePatch) SetName(v string) {
	o.Name = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *OrganizationJsonMergePatch) SetSlug(v string) {
	o.Slug = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetTheme() string {
	if o == nil || IsNil(o.Theme.Get()) {
		var ret string
		return ret
	}
	return *o.Theme.Get()
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetThemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Theme.Get(), o.Theme.IsSet()
}

// HasTheme returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTheme() bool {
	if o != nil && o.Theme.IsSet() {
		return true
	}

	return false
}

// SetTheme gets a reference to the given NullableString and assigns it to the Theme field.
func (o *OrganizationJsonMergePatch) SetTheme(v string) {
	o.Theme.Set(&v)
}
// SetThemeNil sets the value for Theme to be an explicit nil
func (o *OrganizationJsonMergePatch) SetThemeNil() {
	o.Theme.Set(nil)
}

// UnsetTheme ensures that no value is present for Theme, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetTheme() {
	o.Theme.Unset()
}

// GetTierPin returns the TierPin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetTierPin() string {
	if o == nil || IsNil(o.TierPin.Get()) {
		var ret string
		return ret
	}
	return *o.TierPin.Get()
}

// GetTierPinOk returns a tuple with the TierPin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetTierPinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPin.Get(), o.TierPin.IsSet()
}

// HasTierPin returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTierPin() bool {
	if o != nil && o.TierPin.IsSet() {
		return true
	}

	return false
}

// SetTierPin gets a reference to the given NullableString and assigns it to the TierPin field.
func (o *OrganizationJsonMergePatch) SetTierPin(v string) {
	o.TierPin.Set(&v)
}
// SetTierPinNil sets the value for TierPin to be an explicit nil
func (o *OrganizationJsonMergePatch) SetTierPinNil() {
	o.TierPin.Set(nil)
}

// UnsetTierPin ensures that no value is present for TierPin, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetTierPin() {
	o.TierPin.Unset()
}

// GetTierPinnedAt returns the TierPinnedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetTierPinnedAt() time.Time {
	if o == nil || IsNil(o.TierPinnedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TierPinnedAt.Get()
}

// GetTierPinnedAtOk returns a tuple with the TierPinnedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetTierPinnedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPinnedAt.Get(), o.TierPinnedAt.IsSet()
}

// HasTierPinnedAt returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTierPinnedAt() bool {
	if o != nil && o.TierPinnedAt.IsSet() {
		return true
	}

	return false
}

// SetTierPinnedAt gets a reference to the given NullableTime and assigns it to the TierPinnedAt field.
func (o *OrganizationJsonMergePatch) SetTierPinnedAt(v time.Time) {
	o.TierPinnedAt.Set(&v)
}
// SetTierPinnedAtNil sets the value for TierPinnedAt to be an explicit nil
func (o *OrganizationJsonMergePatch) SetTierPinnedAtNil() {
	o.TierPinnedAt.Set(nil)
}

// UnsetTierPinnedAt ensures that no value is present for TierPinnedAt, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetTierPinnedAt() {
	o.TierPinnedAt.Unset()
}

// GetTierPinnedBy returns the TierPinnedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetTierPinnedBy() User {
	if o == nil || IsNil(o.TierPinnedBy.Get()) {
		var ret User
		return ret
	}
	return *o.TierPinnedBy.Get()
}

// GetTierPinnedByOk returns a tuple with the TierPinnedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetTierPinnedByOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPinnedBy.Get(), o.TierPinnedBy.IsSet()
}

// HasTierPinnedBy returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTierPinnedBy() bool {
	if o != nil && o.TierPinnedBy.IsSet() {
		return true
	}

	return false
}

// SetTierPinnedBy gets a reference to the given NullableUser and assigns it to the TierPinnedBy field.
func (o *OrganizationJsonMergePatch) SetTierPinnedBy(v User) {
	o.TierPinnedBy.Set(&v)
}
// SetTierPinnedByNil sets the value for TierPinnedBy to be an explicit nil
func (o *OrganizationJsonMergePatch) SetTierPinnedByNil() {
	o.TierPinnedBy.Set(nil)
}

// UnsetTierPinnedBy ensures that no value is present for TierPinnedBy, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetTierPinnedBy() {
	o.TierPinnedBy.Unset()
}

// GetTierPinReason returns the TierPinReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetTierPinReason() string {
	if o == nil || IsNil(o.TierPinReason.Get()) {
		var ret string
		return ret
	}
	return *o.TierPinReason.Get()
}

// GetTierPinReasonOk returns a tuple with the TierPinReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetTierPinReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPinReason.Get(), o.TierPinReason.IsSet()
}

// HasTierPinReason returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTierPinReason() bool {
	if o != nil && o.TierPinReason.IsSet() {
		return true
	}

	return false
}

// SetTierPinReason gets a reference to the given NullableString and assigns it to the TierPinReason field.
func (o *OrganizationJsonMergePatch) SetTierPinReason(v string) {
	o.TierPinReason.Set(&v)
}
// SetTierPinReasonNil sets the value for TierPinReason to be an explicit nil
func (o *OrganizationJsonMergePatch) SetTierPinReasonNil() {
	o.TierPinReason.Set(nil)
}

// UnsetTierPinReason ensures that no value is present for TierPinReason, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetTierPinReason() {
	o.TierPinReason.Unset()
}

// GetLowBalanceWarnedAt returns the LowBalanceWarnedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetLowBalanceWarnedAt() time.Time {
	if o == nil || IsNil(o.LowBalanceWarnedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LowBalanceWarnedAt.Get()
}

// GetLowBalanceWarnedAtOk returns a tuple with the LowBalanceWarnedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetLowBalanceWarnedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LowBalanceWarnedAt.Get(), o.LowBalanceWarnedAt.IsSet()
}

// HasLowBalanceWarnedAt returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasLowBalanceWarnedAt() bool {
	if o != nil && o.LowBalanceWarnedAt.IsSet() {
		return true
	}

	return false
}

// SetLowBalanceWarnedAt gets a reference to the given NullableTime and assigns it to the LowBalanceWarnedAt field.
func (o *OrganizationJsonMergePatch) SetLowBalanceWarnedAt(v time.Time) {
	o.LowBalanceWarnedAt.Set(&v)
}
// SetLowBalanceWarnedAtNil sets the value for LowBalanceWarnedAt to be an explicit nil
func (o *OrganizationJsonMergePatch) SetLowBalanceWarnedAtNil() {
	o.LowBalanceWarnedAt.Set(nil)
}

// UnsetLowBalanceWarnedAt ensures that no value is present for LowBalanceWarnedAt, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetLowBalanceWarnedAt() {
	o.LowBalanceWarnedAt.Unset()
}

// GetTwoFactorRequiredAt returns the TwoFactorRequiredAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetTwoFactorRequiredAt() time.Time {
	if o == nil || IsNil(o.TwoFactorRequiredAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TwoFactorRequiredAt.Get()
}

// GetTwoFactorRequiredAtOk returns a tuple with the TwoFactorRequiredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetTwoFactorRequiredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TwoFactorRequiredAt.Get(), o.TwoFactorRequiredAt.IsSet()
}

// HasTwoFactorRequiredAt returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTwoFactorRequiredAt() bool {
	if o != nil && o.TwoFactorRequiredAt.IsSet() {
		return true
	}

	return false
}

// SetTwoFactorRequiredAt gets a reference to the given NullableTime and assigns it to the TwoFactorRequiredAt field.
func (o *OrganizationJsonMergePatch) SetTwoFactorRequiredAt(v time.Time) {
	o.TwoFactorRequiredAt.Set(&v)
}
// SetTwoFactorRequiredAtNil sets the value for TwoFactorRequiredAt to be an explicit nil
func (o *OrganizationJsonMergePatch) SetTwoFactorRequiredAtNil() {
	o.TwoFactorRequiredAt.Set(nil)
}

// UnsetTwoFactorRequiredAt ensures that no value is present for TwoFactorRequiredAt, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetTwoFactorRequiredAt() {
	o.TwoFactorRequiredAt.Unset()
}

// GetMemberships returns the Memberships field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetMemberships() []Membership {
	if o == nil || IsNil(o.Memberships) {
		var ret []Membership
		return ret
	}
	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetMembershipsOk() ([]Membership, bool) {
	if o == nil || IsNil(o.Memberships) {
		return nil, false
	}
	return o.Memberships, true
}

// HasMemberships returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasMemberships() bool {
	if o != nil && !IsNil(o.Memberships) {
		return true
	}

	return false
}

// SetMemberships gets a reference to the given []Membership and assigns it to the Memberships field.
func (o *OrganizationJsonMergePatch) SetMemberships(v []Membership) {
	o.Memberships = v
}

// GetApplications returns the Applications field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetApplications() []string {
	if o == nil || IsNil(o.Applications) {
		var ret []string
		return ret
	}
	return o.Applications
}

// GetApplicationsOk returns a tuple with the Applications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetApplicationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Applications) {
		return nil, false
	}
	return o.Applications, true
}

// HasApplications returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasApplications() bool {
	if o != nil && !IsNil(o.Applications) {
		return true
	}

	return false
}

// SetApplications gets a reference to the given []string and assigns it to the Applications field.
func (o *OrganizationJsonMergePatch) SetApplications(v []string) {
	o.Applications = v
}

// GetSwarms returns the Swarms field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetSwarms() []string {
	if o == nil || IsNil(o.Swarms) {
		var ret []string
		return ret
	}
	return o.Swarms
}

// GetSwarmsOk returns a tuple with the Swarms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetSwarmsOk() ([]string, bool) {
	if o == nil || IsNil(o.Swarms) {
		return nil, false
	}
	return o.Swarms, true
}

// HasSwarms returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasSwarms() bool {
	if o != nil && !IsNil(o.Swarms) {
		return true
	}

	return false
}

// SetSwarms gets a reference to the given []string and assigns it to the Swarms field.
func (o *OrganizationJsonMergePatch) SetSwarms(v []string) {
	o.Swarms = v
}

// GetMachines returns the Machines field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetMachines() []Machine {
	if o == nil || IsNil(o.Machines) {
		var ret []Machine
		return ret
	}
	return o.Machines
}

// GetMachinesOk returns a tuple with the Machines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetMachinesOk() ([]Machine, bool) {
	if o == nil || IsNil(o.Machines) {
		return nil, false
	}
	return o.Machines, true
}

// HasMachines returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasMachines() bool {
	if o != nil && !IsNil(o.Machines) {
		return true
	}

	return false
}

// SetMachines gets a reference to the given []Machine and assigns it to the Machines field.
func (o *OrganizationJsonMergePatch) SetMachines(v []Machine) {
	o.Machines = v
}

// GetCreditTransactions returns the CreditTransactions field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetCreditTransactions() []string {
	if o == nil || IsNil(o.CreditTransactions) {
		var ret []string
		return ret
	}
	return o.CreditTransactions
}

// GetCreditTransactionsOk returns a tuple with the CreditTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetCreditTransactionsOk() ([]string, bool) {
	if o == nil || IsNil(o.CreditTransactions) {
		return nil, false
	}
	return o.CreditTransactions, true
}

// HasCreditTransactions returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasCreditTransactions() bool {
	if o != nil && !IsNil(o.CreditTransactions) {
		return true
	}

	return false
}

// SetCreditTransactions gets a reference to the given []string and assigns it to the CreditTransactions field.
func (o *OrganizationJsonMergePatch) SetCreditTransactions(v []string) {
	o.CreditTransactions = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetVariables() []Variable {
	if o == nil || IsNil(o.Variables) {
		var ret []Variable
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetVariablesOk() ([]Variable, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []Variable and assigns it to the Variables field.
func (o *OrganizationJsonMergePatch) SetVariables(v []Variable) {
	o.Variables = v
}

// GetSignals returns the Signals field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetSignals() []OrganizationSignal {
	if o == nil || IsNil(o.Signals) {
		var ret []OrganizationSignal
		return ret
	}
	return o.Signals
}

// GetSignalsOk returns a tuple with the Signals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetSignalsOk() ([]OrganizationSignal, bool) {
	if o == nil || IsNil(o.Signals) {
		return nil, false
	}
	return o.Signals, true
}

// HasSignals returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasSignals() bool {
	if o != nil && !IsNil(o.Signals) {
		return true
	}

	return false
}

// SetSignals gets a reference to the given []OrganizationSignal and assigns it to the Signals field.
func (o *OrganizationJsonMergePatch) SetSignals(v []OrganizationSignal) {
	o.Signals = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrganizationJsonMergePatch) SetId(v string) {
	o.Id = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *OrganizationJsonMergePatch) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *OrganizationJsonMergePatch) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *OrganizationJsonMergePatch) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationJsonMergePatch) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationJsonMergePatch) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *OrganizationJsonMergePatch) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *OrganizationJsonMergePatch) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *OrganizationJsonMergePatch) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetTierPinned returns the TierPinned field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetTierPinned() bool {
	if o == nil || IsNil(o.TierPinned) {
		var ret bool
		return ret
	}
	return *o.TierPinned
}

// GetTierPinnedOk returns a tuple with the TierPinned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetTierPinnedOk() (*bool, bool) {
	if o == nil || IsNil(o.TierPinned) {
		return nil, false
	}
	return o.TierPinned, true
}

// HasTierPinned returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasTierPinned() bool {
	if o != nil && !IsNil(o.TierPinned) {
		return true
	}

	return false
}

// SetTierPinned gets a reference to the given bool and assigns it to the TierPinned field.
func (o *OrganizationJsonMergePatch) SetTierPinned(v bool) {
	o.TierPinned = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *OrganizationJsonMergePatch) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationJsonMergePatch) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *OrganizationJsonMergePatch) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *OrganizationJsonMergePatch) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o OrganizationJsonMergePatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationJsonMergePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MachineAccount.IsSet() {
		toSerialize["machineAccount"] = o.MachineAccount.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if o.Theme.IsSet() {
		toSerialize["theme"] = o.Theme.Get()
	}
	if o.TierPin.IsSet() {
		toSerialize["tierPin"] = o.TierPin.Get()
	}
	if o.TierPinnedAt.IsSet() {
		toSerialize["tierPinnedAt"] = o.TierPinnedAt.Get()
	}
	if o.TierPinnedBy.IsSet() {
		toSerialize["tierPinnedBy"] = o.TierPinnedBy.Get()
	}
	if o.TierPinReason.IsSet() {
		toSerialize["tierPinReason"] = o.TierPinReason.Get()
	}
	if o.LowBalanceWarnedAt.IsSet() {
		toSerialize["lowBalanceWarnedAt"] = o.LowBalanceWarnedAt.Get()
	}
	if o.TwoFactorRequiredAt.IsSet() {
		toSerialize["twoFactorRequiredAt"] = o.TwoFactorRequiredAt.Get()
	}
	if !IsNil(o.Memberships) {
		toSerialize["memberships"] = o.Memberships
	}
	if !IsNil(o.Applications) {
		toSerialize["applications"] = o.Applications
	}
	if !IsNil(o.Swarms) {
		toSerialize["swarms"] = o.Swarms
	}
	if !IsNil(o.Machines) {
		toSerialize["machines"] = o.Machines
	}
	if !IsNil(o.CreditTransactions) {
		toSerialize["creditTransactions"] = o.CreditTransactions
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !IsNil(o.Signals) {
		toSerialize["signals"] = o.Signals
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deletedAt"] = o.DeletedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if !IsNil(o.TierPinned) {
		toSerialize["tierPinned"] = o.TierPinned
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableOrganizationJsonMergePatch struct {
	value *OrganizationJsonMergePatch
	isSet bool
}

func (v NullableOrganizationJsonMergePatch) Get() *OrganizationJsonMergePatch {
	return v.value
}

func (v *NullableOrganizationJsonMergePatch) Set(val *OrganizationJsonMergePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationJsonMergePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationJsonMergePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationJsonMergePatch(val *OrganizationJsonMergePatch) *NullableOrganizationJsonMergePatch {
	return &NullableOrganizationJsonMergePatch{value: val, isSet: true}
}

func (v NullableOrganizationJsonMergePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationJsonMergePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


