/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the RecoveryCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoveryCode{}

// RecoveryCode struct for RecoveryCode
type RecoveryCode struct {
	User *User `json:"user,omitempty"`
	// SHA-256 hex digest of the plaintext code; the only copy that is ever stored.
	CodeHash *string `json:"codeHash,omitempty"`
	// When this code was spent; null means it is still usable.
	UsedAt NullableTime `json:"usedAt,omitempty"`
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
	Used *bool `json:"used,omitempty"`
}

// NewRecoveryCode instantiates a new RecoveryCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoveryCode() *RecoveryCode {
	this := RecoveryCode{}
	return &this
}

// NewRecoveryCodeWithDefaults instantiates a new RecoveryCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoveryCodeWithDefaults() *RecoveryCode {
	this := RecoveryCode{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *RecoveryCode) GetUser() User {
	if o == nil || IsNil(o.User) {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryCode) GetUserOk() (*User, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *RecoveryCode) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *RecoveryCode) SetUser(v User) {
	o.User = &v
}

// GetCodeHash returns the CodeHash field value if set, zero value otherwise.
func (o *RecoveryCode) GetCodeHash() string {
	if o == nil || IsNil(o.CodeHash) {
		var ret string
		return ret
	}
	return *o.CodeHash
}

// GetCodeHashOk returns a tuple with the CodeHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryCode) GetCodeHashOk() (*string, bool) {
	if o == nil || IsNil(o.CodeHash) {
		return nil, false
	}
	return o.CodeHash, true
}

// HasCodeHash returns a boolean if a field has been set.
func (o *RecoveryCode) HasCodeHash() bool {
	if o != nil && !IsNil(o.CodeHash) {
		return true
	}

	return false
}

// SetCodeHash gets a reference to the given string and assigns it to the CodeHash field.
func (o *RecoveryCode) SetCodeHash(v string) {
	o.CodeHash = &v
}

// GetUsedAt returns the UsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecoveryCode) GetUsedAt() time.Time {
	if o == nil || IsNil(o.UsedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UsedAt.Get()
}

// GetUsedAtOk returns a tuple with the UsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecoveryCode) GetUsedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsedAt.Get(), o.UsedAt.IsSet()
}

// HasUsedAt returns a boolean if a field has been set.
func (o *RecoveryCode) HasUsedAt() bool {
	if o != nil && o.UsedAt.IsSet() {
		return true
	}

	return false
}

// SetUsedAt gets a reference to the given NullableTime and assigns it to the UsedAt field.
func (o *RecoveryCode) SetUsedAt(v time.Time) {
	o.UsedAt.Set(&v)
}
// SetUsedAtNil sets the value for UsedAt to be an explicit nil
func (o *RecoveryCode) SetUsedAtNil() {
	o.UsedAt.Set(nil)
}

// UnsetUsedAt ensures that no value is present for UsedAt, not even an explicit nil
func (o *RecoveryCode) UnsetUsedAt() {
	o.UsedAt.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RecoveryCode) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryCode) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RecoveryCode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RecoveryCode) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RecoveryCode) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryCode) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RecoveryCode) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *RecoveryCode) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecoveryCode) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecoveryCode) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *RecoveryCode) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *RecoveryCode) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *RecoveryCode) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *RecoveryCode) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *RecoveryCode) GetUsed() bool {
	if o == nil || IsNil(o.Used) {
		var ret bool
		return ret
	}
	return *o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryCode) GetUsedOk() (*bool, bool) {
	if o == nil || IsNil(o.Used) {
		return nil, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *RecoveryCode) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given bool and assigns it to the Used field.
func (o *RecoveryCode) SetUsed(v bool) {
	o.Used = &v
}

func (o RecoveryCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoveryCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.CodeHash) {
		toSerialize["codeHash"] = o.CodeHash
	}
	if o.UsedAt.IsSet() {
		toSerialize["usedAt"] = o.UsedAt.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	return toSerialize, nil
}

type NullableRecoveryCode struct {
	value *RecoveryCode
	isSet bool
}

func (v NullableRecoveryCode) Get() *RecoveryCode {
	return v.value
}

func (v *NullableRecoveryCode) Set(val *RecoveryCode) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoveryCode) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoveryCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoveryCode(val *RecoveryCode) *NullableRecoveryCode {
	return &NullableRecoveryCode{value: val, isSet: true}
}

func (v NullableRecoveryCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoveryCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


