/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the SwarmNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwarmNode{}

// SwarmNode struct for SwarmNode
type SwarmNode struct {
	Swarm *string `json:"swarm,omitempty"`
	// The swarm-assigned node id.
	NodeId *string `json:"nodeId,omitempty"`
	Hostname NullableString `json:"hostname,omitempty"`
	State NullableString `json:"state,omitempty"`
	// This node's share of the cluster's capacity, as the reconciler read it.
	Capacity map[string]string `json:"capacity,omitempty"`
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
}

// NewSwarmNode instantiates a new SwarmNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwarmNode() *SwarmNode {
	this := SwarmNode{}
	return &this
}

// NewSwarmNodeWithDefaults instantiates a new SwarmNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwarmNodeWithDefaults() *SwarmNode {
	this := SwarmNode{}
	return &this
}

// GetSwarm returns the Swarm field value if set, zero value otherwise.
func (o *SwarmNode) GetSwarm() string {
	if o == nil || IsNil(o.Swarm) {
		var ret string
		return ret
	}
	return *o.Swarm
}

// GetSwarmOk returns a tuple with the Swarm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwarmNode) GetSwarmOk() (*string, bool) {
	if o == nil || IsNil(o.Swarm) {
		return nil, false
	}
	return o.Swarm, true
}

// HasSwarm returns a boolean if a field has been set.
func (o *SwarmNode) HasSwarm() bool {
	if o != nil && !IsNil(o.Swarm) {
		return true
	}

	return false
}

// SetSwarm gets a reference to the given string and assigns it to the Swarm field.
func (o *SwarmNode) SetSwarm(v string) {
	o.Swarm = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *SwarmNode) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwarmNode) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *SwarmNode) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *SwarmNode) SetNodeId(v string) {
	o.NodeId = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SwarmNode) GetHostname() string {
	if o == nil || IsNil(o.Hostname.Get()) {
		var ret string
		return ret
	}
	return *o.Hostname.Get()
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SwarmNode) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hostname.Get(), o.Hostname.IsSet()
}

// HasHostname returns a boolean if a field has been set.
func (o *SwarmNode) HasHostname() bool {
	if o != nil && o.Hostname.IsSet() {
		return true
	}

	return false
}

// SetHostname gets a reference to the given NullableString and assigns it to the Hostname field.
func (o *SwarmNode) SetHostname(v string) {
	o.Hostname.Set(&v)
}
// SetHostnameNil sets the value for Hostname to be an explicit nil
func (o *SwarmNode) SetHostnameNil() {
	o.Hostname.Set(nil)
}

// UnsetHostname ensures that no value is present for Hostname, not even an explicit nil
func (o *SwarmNode) UnsetHostname() {
	o.Hostname.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SwarmNode) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SwarmNode) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *SwarmNode) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *SwarmNode) SetState(v string) {
	o.State.Set(&v)
}
// SetStateNil sets the value for State to be an explicit nil
func (o *SwarmNode) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *SwarmNode) UnsetState() {
	o.State.Unset()
}

// GetCapacity returns the Capacity field value if set, zero value otherwise.
func (o *SwarmNode) GetCapacity() map[string]string {
	if o == nil || IsNil(o.Capacity) {
		var ret map[string]string
		return ret
	}
	return o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwarmNode) GetCapacityOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Capacity) {
		return map[string]string{}, false
	}
	return o.Capacity, true
}

// HasCapacity returns a boolean if a field has been set.
func (o *SwarmNode) HasCapacity() bool {
	if o != nil && !IsNil(o.Capacity) {
		return true
	}

	return false
}

// SetCapacity gets a reference to the given map[string]string and assigns it to the Capacity field.
func (o *SwarmNode) SetCapacity(v map[string]string) {
	o.Capacity = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SwarmNode) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwarmNode) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SwarmNode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SwarmNode) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SwarmNode) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwarmNode) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SwarmNode) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *SwarmNode) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SwarmNode) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SwarmNode) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SwarmNode) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *SwarmNode) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *SwarmNode) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *SwarmNode) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o SwarmNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwarmNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Swarm) {
		toSerialize["swarm"] = o.Swarm
	}
	if !IsNil(o.NodeId) {
		toSerialize["nodeId"] = o.NodeId
	}
	if o.Hostname.IsSet() {
		toSerialize["hostname"] = o.Hostname.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if !IsNil(o.Capacity) {
		toSerialize["capacity"] = o.Capacity
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

type NullableSwarmNode struct {
	value *SwarmNode
	isSet bool
}

func (v NullableSwarmNode) Get() *SwarmNode {
	return v.value
}

func (v *NullableSwarmNode) Set(val *SwarmNode) {
	v.value = val
	v.isSet = true
}

func (v NullableSwarmNode) IsSet() bool {
	return v.isSet
}

func (v *NullableSwarmNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwarmNode(val *SwarmNode) *NullableSwarmNode {
	return &NullableSwarmNode{value: val, isSet: true}
}

func (v NullableSwarmNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwarmNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


