/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the PortAllocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortAllocation{}

// PortAllocation struct for PortAllocation
type PortAllocation struct {
	// The cluster this port is claimed on. Deleting the cluster takes its allocations with it — a reservation on a swarm that no longer exists is not holding anything back.
	Swarm *string `json:"swarm,omitempty"`
	Application *string `json:"application,omitempty"`
	// The deployment name this reservation belongs to — {@see Deployment::$name}, or `''` for a revision that carries no name (before the field existed, or a client that never sent one), which is its own stable scope rather than a wildcard: every unnamed revision of an application shares it, exactly the single continuous scope every application had before this column existed.
	DeploymentName *string `json:"deploymentName,omitempty"`
	// The compose service name, as the customer's file spells it.
	ServiceName *string `json:"serviceName,omitempty"`
	// The container port traffic is forwarded to.
	TargetPort *int32 `json:"targetPort,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	// What the world connects to. Unique per protocol on this cluster.
	PublishedPort *int32 `json:"publishedPort,omitempty"`
	// Whether the platform chose this number or the compose file did.
	Assigned *bool `json:"assigned,omitempty"`
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
}

// NewPortAllocation instantiates a new PortAllocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortAllocation() *PortAllocation {
	this := PortAllocation{}
	return &this
}

// NewPortAllocationWithDefaults instantiates a new PortAllocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortAllocationWithDefaults() *PortAllocation {
	this := PortAllocation{}
	return &this
}

// GetSwarm returns the Swarm field value if set, zero value otherwise.
func (o *PortAllocation) GetSwarm() string {
	if o == nil || IsNil(o.Swarm) {
		var ret string
		return ret
	}
	return *o.Swarm
}

// GetSwarmOk returns a tuple with the Swarm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetSwarmOk() (*string, bool) {
	if o == nil || IsNil(o.Swarm) {
		return nil, false
	}
	return o.Swarm, true
}

// HasSwarm returns a boolean if a field has been set.
func (o *PortAllocation) HasSwarm() bool {
	if o != nil && !IsNil(o.Swarm) {
		return true
	}

	return false
}

// SetSwarm gets a reference to the given string and assigns it to the Swarm field.
func (o *PortAllocation) SetSwarm(v string) {
	o.Swarm = &v
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *PortAllocation) GetApplication() string {
	if o == nil || IsNil(o.Application) {
		var ret string
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetApplicationOk() (*string, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *PortAllocation) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given string and assigns it to the Application field.
func (o *PortAllocation) SetApplication(v string) {
	o.Application = &v
}

// GetDeploymentName returns the DeploymentName field value if set, zero value otherwise.
func (o *PortAllocation) GetDeploymentName() string {
	if o == nil || IsNil(o.DeploymentName) {
		var ret string
		return ret
	}
	return *o.DeploymentName
}

// GetDeploymentNameOk returns a tuple with the DeploymentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetDeploymentNameOk() (*string, bool) {
	if o == nil || IsNil(o.DeploymentName) {
		return nil, false
	}
	return o.DeploymentName, true
}

// HasDeploymentName returns a boolean if a field has been set.
func (o *PortAllocation) HasDeploymentName() bool {
	if o != nil && !IsNil(o.DeploymentName) {
		return true
	}

	return false
}

// SetDeploymentName gets a reference to the given string and assigns it to the DeploymentName field.
func (o *PortAllocation) SetDeploymentName(v string) {
	o.DeploymentName = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *PortAllocation) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *PortAllocation) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *PortAllocation) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetTargetPort returns the TargetPort field value if set, zero value otherwise.
func (o *PortAllocation) GetTargetPort() int32 {
	if o == nil || IsNil(o.TargetPort) {
		var ret int32
		return ret
	}
	return *o.TargetPort
}

// GetTargetPortOk returns a tuple with the TargetPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetTargetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.TargetPort) {
		return nil, false
	}
	return o.TargetPort, true
}

// HasTargetPort returns a boolean if a field has been set.
func (o *PortAllocation) HasTargetPort() bool {
	if o != nil && !IsNil(o.TargetPort) {
		return true
	}

	return false
}

// SetTargetPort gets a reference to the given int32 and assigns it to the TargetPort field.
func (o *PortAllocation) SetTargetPort(v int32) {
	o.TargetPort = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *PortAllocation) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *PortAllocation) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *PortAllocation) SetProtocol(v string) {
	o.Protocol = &v
}

// GetPublishedPort returns the PublishedPort field value if set, zero value otherwise.
func (o *PortAllocation) GetPublishedPort() int32 {
	if o == nil || IsNil(o.PublishedPort) {
		var ret int32
		return ret
	}
	return *o.PublishedPort
}

// GetPublishedPortOk returns a tuple with the PublishedPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetPublishedPortOk() (*int32, bool) {
	if o == nil || IsNil(o.PublishedPort) {
		return nil, false
	}
	return o.PublishedPort, true
}

// HasPublishedPort returns a boolean if a field has been set.
func (o *PortAllocation) HasPublishedPort() bool {
	if o != nil && !IsNil(o.PublishedPort) {
		return true
	}

	return false
}

// SetPublishedPort gets a reference to the given int32 and assigns it to the PublishedPort field.
func (o *PortAllocation) SetPublishedPort(v int32) {
	o.PublishedPort = &v
}

// GetAssigned returns the Assigned field value if set, zero value otherwise.
func (o *PortAllocation) GetAssigned() bool {
	if o == nil || IsNil(o.Assigned) {
		var ret bool
		return ret
	}
	return *o.Assigned
}

// GetAssignedOk returns a tuple with the Assigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetAssignedOk() (*bool, bool) {
	if o == nil || IsNil(o.Assigned) {
		return nil, false
	}
	return o.Assigned, true
}

// HasAssigned returns a boolean if a field has been set.
func (o *PortAllocation) HasAssigned() bool {
	if o != nil && !IsNil(o.Assigned) {
		return true
	}

	return false
}

// SetAssigned gets a reference to the given bool and assigns it to the Assigned field.
func (o *PortAllocation) SetAssigned(v bool) {
	o.Assigned = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PortAllocation) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PortAllocation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PortAllocation) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PortAllocation) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortAllocation) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PortAllocation) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PortAllocation) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PortAllocation) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PortAllocation) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PortAllocation) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *PortAllocation) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *PortAllocation) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *PortAllocation) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o PortAllocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortAllocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Swarm) {
		toSerialize["swarm"] = o.Swarm
	}
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}
	if !IsNil(o.DeploymentName) {
		toSerialize["deploymentName"] = o.DeploymentName
	}
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	if !IsNil(o.TargetPort) {
		toSerialize["targetPort"] = o.TargetPort
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.PublishedPort) {
		toSerialize["publishedPort"] = o.PublishedPort
	}
	if !IsNil(o.Assigned) {
		toSerialize["assigned"] = o.Assigned
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

type NullablePortAllocation struct {
	value *PortAllocation
	isSet bool
}

func (v NullablePortAllocation) Get() *PortAllocation {
	return v.value
}

func (v *NullablePortAllocation) Set(val *PortAllocation) {
	v.value = val
	v.isSet = true
}

func (v NullablePortAllocation) IsSet() bool {
	return v.isSet
}

func (v *NullablePortAllocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortAllocation(val *PortAllocation) *NullablePortAllocation {
	return &NullablePortAllocation{value: val, isSet: true}
}

func (v NullablePortAllocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortAllocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


