/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"fmt"
)


// ServiceMemReservation Memory floor in bytes (`deploy.resources.reservations.memory`), null = nothing declared.
type ServiceMemReservation struct {
	Int32 *int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ServiceMemReservation) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ServiceMemReservation)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ServiceMemReservation) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableServiceMemReservation struct {
	value *ServiceMemReservation
	isSet bool
}

func (v NullableServiceMemReservation) Get() *ServiceMemReservation {
	return v.value
}

func (v *NullableServiceMemReservation) Set(val *ServiceMemReservation) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceMemReservation) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceMemReservation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceMemReservation(val *ServiceMemReservation) *NullableServiceMemReservation {
	return &NullableServiceMemReservation{value: val, isSet: true}
}

func (v NullableServiceMemReservation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceMemReservation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


