/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeploymentBundleUploadConfirmInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentBundleUploadConfirmInput{}

// DeploymentBundleUploadConfirmInput An IMMUTABLE compose revision. A deploy is a new row; rollback re-points Application::$currentDeployment at an older one. Placement is resolved onto this row (targetSwarm) at deploy time, so migration is just the next revision.
type DeploymentBundleUploadConfirmInput struct {
	// Raw `build.secrets` values, keyed by service then by BuildKit secret id (Grey.ooo/someones.computer_agent#46) — matches `App\\Service\\Bundle\\BundleIngestor::commitFromStoredContent()`'s `$secrets` parameter.
	Secrets map[string]map[string]string `json:"secrets,omitempty"`
	Application NullableString `json:"application"`
	// Matches `App\\Service\\Bundle\\BundleManifest::$client` — which client produced this.
	Client string `json:"client"`
	Name NullableString `json:"name,omitempty"`
	// Ask for a new revision even if this digest already matches one — {@see BundleManifest::$force}'s own meaning, unchanged.
	Force *bool `json:"force,omitempty"`
	Compose string `json:"compose"`
	Contexts []BundleContextInput `json:"contexts,omitempty"`
	Images []BundleForwardedImageInput `json:"images,omitempty"`
}

type _DeploymentBundleUploadConfirmInput DeploymentBundleUploadConfirmInput

// NewDeploymentBundleUploadConfirmInput instantiates a new DeploymentBundleUploadConfirmInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentBundleUploadConfirmInput(application NullableString, client string, compose string) *DeploymentBundleUploadConfirmInput {
	this := DeploymentBundleUploadConfirmInput{}
	this.Application = application
	this.Client = client
	var force bool = false
	this.Force = &force
	this.Compose = compose
	return &this
}

// NewDeploymentBundleUploadConfirmInputWithDefaults instantiates a new DeploymentBundleUploadConfirmInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentBundleUploadConfirmInputWithDefaults() *DeploymentBundleUploadConfirmInput {
	this := DeploymentBundleUploadConfirmInput{}
	var client string = "api"
	this.Client = client
	var force bool = false
	this.Force = &force
	var compose string = ""
	this.Compose = compose
	return &this
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *DeploymentBundleUploadConfirmInput) GetSecrets() map[string]map[string]string {
	if o == nil || IsNil(o.Secrets) {
		var ret map[string]map[string]string
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadConfirmInput) GetSecretsOk() (map[string]map[string]string, bool) {
	if o == nil || IsNil(o.Secrets) {
		return map[string]map[string]string{}, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *DeploymentBundleUploadConfirmInput) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given map[string]map[string]string and assigns it to the Secrets field.
func (o *DeploymentBundleUploadConfirmInput) SetSecrets(v map[string]map[string]string) {
	o.Secrets = v
}

// GetApplication returns the Application field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DeploymentBundleUploadConfirmInput) GetApplication() string {
	if o == nil || o.Application.Get() == nil {
		var ret string
		return ret
	}

	return *o.Application.Get()
}

// GetApplicationOk returns a tuple with the Application field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentBundleUploadConfirmInput) GetApplicationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Application.Get(), o.Application.IsSet()
}

// SetApplication sets field value
func (o *DeploymentBundleUploadConfirmInput) SetApplication(v string) {
	o.Application.Set(&v)
}

// GetClient returns the Client field value
func (o *DeploymentBundleUploadConfirmInput) GetClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadConfirmInput) GetClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Client, true
}

// SetClient sets field value
func (o *DeploymentBundleUploadConfirmInput) SetClient(v string) {
	o.Client = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentBundleUploadConfirmInput) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentBundleUploadConfirmInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *DeploymentBundleUploadConfirmInput) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *DeploymentBundleUploadConfirmInput) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *DeploymentBundleUploadConfirmInput) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *DeploymentBundleUploadConfirmInput) UnsetName() {
	o.Name.Unset()
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *DeploymentBundleUploadConfirmInput) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadConfirmInput) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *DeploymentBundleUploadConfirmInput) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *DeploymentBundleUploadConfirmInput) SetForce(v bool) {
	o.Force = &v
}

// GetCompose returns the Compose field value
func (o *DeploymentBundleUploadConfirmInput) GetCompose() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Compose
}

// GetComposeOk returns a tuple with the Compose field value
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadConfirmInput) GetComposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Compose, true
}

// SetCompose sets field value
func (o *DeploymentBundleUploadConfirmInput) SetCompose(v string) {
	o.Compose = v
}

// GetContexts returns the Contexts field value if set, zero value otherwise.
func (o *DeploymentBundleUploadConfirmInput) GetContexts() []BundleContextInput {
	if o == nil || IsNil(o.Contexts) {
		var ret []BundleContextInput
		return ret
	}
	return o.Contexts
}

// GetContextsOk returns a tuple with the Contexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadConfirmInput) GetContextsOk() ([]BundleContextInput, bool) {
	if o == nil || IsNil(o.Contexts) {
		return nil, false
	}
	return o.Contexts, true
}

// HasContexts returns a boolean if a field has been set.
func (o *DeploymentBundleUploadConfirmInput) HasContexts() bool {
	if o != nil && !IsNil(o.Contexts) {
		return true
	}

	return false
}

// SetContexts gets a reference to the given []BundleContextInput and assigns it to the Contexts field.
func (o *DeploymentBundleUploadConfirmInput) SetContexts(v []BundleContextInput) {
	o.Contexts = v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *DeploymentBundleUploadConfirmInput) GetImages() []BundleForwardedImageInput {
	if o == nil || IsNil(o.Images) {
		var ret []BundleForwardedImageInput
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentBundleUploadConfirmInput) GetImagesOk() ([]BundleForwardedImageInput, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *DeploymentBundleUploadConfirmInput) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []BundleForwardedImageInput and assigns it to the Images field.
func (o *DeploymentBundleUploadConfirmInput) SetImages(v []BundleForwardedImageInput) {
	o.Images = v
}

func (o DeploymentBundleUploadConfirmInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentBundleUploadConfirmInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	toSerialize["application"] = o.Application.Get()
	toSerialize["client"] = o.Client
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	toSerialize["compose"] = o.Compose
	if !IsNil(o.Contexts) {
		toSerialize["contexts"] = o.Contexts
	}
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	return toSerialize, nil
}

func (o *DeploymentBundleUploadConfirmInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application",
		"client",
		"compose",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentBundleUploadConfirmInput := _DeploymentBundleUploadConfirmInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentBundleUploadConfirmInput)

	if err != nil {
		return err
	}

	*o = DeploymentBundleUploadConfirmInput(varDeploymentBundleUploadConfirmInput)

	return err
}

type NullableDeploymentBundleUploadConfirmInput struct {
	value *DeploymentBundleUploadConfirmInput
	isSet bool
}

func (v NullableDeploymentBundleUploadConfirmInput) Get() *DeploymentBundleUploadConfirmInput {
	return v.value
}

func (v *NullableDeploymentBundleUploadConfirmInput) Set(val *DeploymentBundleUploadConfirmInput) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentBundleUploadConfirmInput) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentBundleUploadConfirmInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentBundleUploadConfirmInput(val *DeploymentBundleUploadConfirmInput) *NullableDeploymentBundleUploadConfirmInput {
	return &NullableDeploymentBundleUploadConfirmInput{value: val, isSet: true}
}

func (v NullableDeploymentBundleUploadConfirmInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentBundleUploadConfirmInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


