/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	Email *string `json:"email,omitempty"`
	// Handle the user can sign in with instead of their email.
	Username *string `json:"username,omitempty"`
	DisplayName NullableString `json:"displayName,omitempty"`
	// Which skin this person prefers, or null to take whatever their organization or the instance says.
	Theme NullableString `json:"theme,omitempty"`
	// Which locale this person prefers, or null for no explicit choice — the same shape as {@see self::$theme}: null is not `en_GB`, it is \"let the cascade decide\" (cookie, then `Accept-Language`, then the instance default). See {@see \\App\\Service\\LocaleResolver} and docs/internationalization.md.
	Locale NullableString `json:"locale,omitempty"`
	// The IANA timezone identifier (e.g. `Europe/London`) this person prefers, or null for no explicit choice — the same shape as {@see self::$locale}: null is not UTC, it is \"let the cascade decide\" (cookie written by the browser's own auto-detection, then the instance default). A plain validated string rather than a backed enum like {@see self::$theme}/{@see self::$locale}: the IANA database has ~400 identifiers, too many for an enum to curate the way {@see \\App\\Enum\\Locale} deliberately does for its two cases. See {@see \\App\\Service\\TimezoneResolver}.
	Timezone NullableString `json:"timezone,omitempty"`
	// Hashed password; null for accounts that authenticate only via OAuth or LDAP.
	Password NullableString `json:"password,omitempty"`
	// The bound entry's distinguished name in LLDAP. Presence means the account is LDAP-authoritative: {@see App\\Service\\LdapAccountLinker} clears any local password when it sets this, and it is never set alongside one.
	LdapDn NullableString `json:"ldapDn,omitempty"`
	AvatarPhoto NullableUserAvatarPhoto `json:"avatarPhoto,omitempty"`
	Roles []string `json:"roles,omitempty"`
	// Set when a platform operator suspends the account; null = active.
	DisabledAt NullableTime `json:"disabledAt,omitempty"`
	// When an operator judged this account to be spam; null = not spam.
	SpamMarkedAt NullableTime `json:"spamMarkedAt,omitempty"`
	SpamMarkedBy NullableUser `json:"spamMarkedBy,omitempty"`
	// When an operator approved the account; null means it is still waiting and can reach nothing but the holding page ({@see self::getRoles()}).
	ApprovedAt NullableTime `json:"approvedAt,omitempty"`
	// When the address on this account was proven to be one the person can read; null means it never was ({@see \\App\\Service\\EmailConfirmationService}).
	EmailConfirmedAt NullableTime `json:"emailConfirmedAt,omitempty"`
	// When the one-off signup credit was granted ({@see \\App\\Service\\Credit\\SignupGrant}).
	CreditGrantedAt NullableTime `json:"creditGrantedAt,omitempty"`
	// An operator's override of the trust tier this account would otherwise progress into on its own; null means the automatic rule decides ({@see \\App\\Service\\Trust\\TierResolver}).
	TierPin NullableString `json:"tierPin,omitempty"`
	TierPinnedAt NullableTime `json:"tierPinnedAt,omitempty"`
	TierPinnedBy NullableUser `json:"tierPinnedBy,omitempty"`
	TierPinReason NullableString `json:"tierPinReason,omitempty"`
	Memberships []Membership `json:"memberships,omitempty"`
	OauthIdentities []OAuthIdentity `json:"oauthIdentities,omitempty"`
	// The TOTP shared secret, **encrypted at rest** ({@see \\App\\Service\\TwoFactor\\TotpSecretCipher}), or null for an account that has not enabled a second factor.
	TotpSecret NullableString `json:"totpSecret,omitempty"`
	// Which key wrapped {@see self::$totpSecret}, so a key rotation can re-wrap it without users re-enrolling ({@see \\App\\Service\\TwoFactor\\TotpSecretCipher}).
	TotpSecretKeyId NullableString `json:"totpSecretKeyId,omitempty"`
	// When the person proved the authenticator by entering a live code; null means 2FA is not in force for this account. This is the flag the step-up gate reads ({@see \\App\\EventSubscriber\\TwoFactorStepUpSubscriber}).
	TotpConfirmedAt NullableTime `json:"totpConfirmedAt,omitempty"`
	RecoveryCodes []RecoveryCode `json:"recoveryCodes,omitempty"`
	// The organization this account exists to act for, or null for a person.
	MachineFor NullableString `json:"machineFor,omitempty"`
	Id *string `json:"id,omitempty"`
	DeletedAt NullableTime `json:"deletedAt,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
	// How this person is named in the UI. Registration requires a display name, but an OAuth provider may not share one, so the handle stands in — never the email address, which is not ours to show.
	DisplayLabel *string `json:"displayLabel,omitempty"`
	// Whether this account is a machine acting for an organization, not a person.
	Machine *bool `json:"machine,omitempty"`
	LdapManaged *bool `json:"ldapManaged,omitempty"`
	AvatarPhotoType NullableString `json:"avatarPhotoType,omitempty"`
	// The identifier stored in the session token. Sign-in accepts either the email or the username ({@see UserRepository::loadUserByIdentifier()}); this is the canonical one the token is refreshed from.
	UserIdentifier *string `json:"userIdentifier,omitempty"`
	// The roles the account actually carries, whether or not it has been approved — what the admin panel shows and what the feature toggles flip.
	GrantedRoles []string `json:"grantedRoles,omitempty"`
	Disabled *bool `json:"disabled,omitempty"`
	Spam *bool `json:"spam,omitempty"`
	Approved *bool `json:"approved,omitempty"`
	EmailConfirmed *bool `json:"emailConfirmed,omitempty"`
	TierPinned *bool `json:"tierPinned,omitempty"`
	// True once the person has proved the authenticator — the gate's on/off switch.
	TotpEnabled *bool `json:"totpEnabled,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
}

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser() *User {
	this := User{}
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *User) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *User) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *User) SetEmail(v string) {
	o.Email = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *User) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *User) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *User) SetUsername(v string) {
	o.Username = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *User) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *User) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *User) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *User) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetTheme returns the Theme field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTheme() string {
	if o == nil || IsNil(o.Theme.Get()) {
		var ret string
		return ret
	}
	return *o.Theme.Get()
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetThemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Theme.Get(), o.Theme.IsSet()
}

// HasTheme returns a boolean if a field has been set.
func (o *User) HasTheme() bool {
	if o != nil && o.Theme.IsSet() {
		return true
	}

	return false
}

// SetTheme gets a reference to the given NullableString and assigns it to the Theme field.
func (o *User) SetTheme(v string) {
	o.Theme.Set(&v)
}
// SetThemeNil sets the value for Theme to be an explicit nil
func (o *User) SetThemeNil() {
	o.Theme.Set(nil)
}

// UnsetTheme ensures that no value is present for Theme, not even an explicit nil
func (o *User) UnsetTheme() {
	o.Theme.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *User) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *User) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *User) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *User) UnsetLocale() {
	o.Locale.Unset()
}

// GetTimezone returns the Timezone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTimezone() string {
	if o == nil || IsNil(o.Timezone.Get()) {
		var ret string
		return ret
	}
	return *o.Timezone.Get()
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timezone.Get(), o.Timezone.IsSet()
}

// HasTimezone returns a boolean if a field has been set.
func (o *User) HasTimezone() bool {
	if o != nil && o.Timezone.IsSet() {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given NullableString and assigns it to the Timezone field.
func (o *User) SetTimezone(v string) {
	o.Timezone.Set(&v)
}
// SetTimezoneNil sets the value for Timezone to be an explicit nil
func (o *User) SetTimezoneNil() {
	o.Timezone.Set(nil)
}

// UnsetTimezone ensures that no value is present for Timezone, not even an explicit nil
func (o *User) UnsetTimezone() {
	o.Timezone.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *User) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *User) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *User) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *User) UnsetPassword() {
	o.Password.Unset()
}

// GetLdapDn returns the LdapDn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetLdapDn() string {
	if o == nil || IsNil(o.LdapDn.Get()) {
		var ret string
		return ret
	}
	return *o.LdapDn.Get()
}

// GetLdapDnOk returns a tuple with the LdapDn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetLdapDnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LdapDn.Get(), o.LdapDn.IsSet()
}

// HasLdapDn returns a boolean if a field has been set.
func (o *User) HasLdapDn() bool {
	if o != nil && o.LdapDn.IsSet() {
		return true
	}

	return false
}

// SetLdapDn gets a reference to the given NullableString and assigns it to the LdapDn field.
func (o *User) SetLdapDn(v string) {
	o.LdapDn.Set(&v)
}
// SetLdapDnNil sets the value for LdapDn to be an explicit nil
func (o *User) SetLdapDnNil() {
	o.LdapDn.Set(nil)
}

// UnsetLdapDn ensures that no value is present for LdapDn, not even an explicit nil
func (o *User) UnsetLdapDn() {
	o.LdapDn.Unset()
}

// GetAvatarPhoto returns the AvatarPhoto field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetAvatarPhoto() UserAvatarPhoto {
	if o == nil || IsNil(o.AvatarPhoto.Get()) {
		var ret UserAvatarPhoto
		return ret
	}
	return *o.AvatarPhoto.Get()
}

// GetAvatarPhotoOk returns a tuple with the AvatarPhoto field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetAvatarPhotoOk() (*UserAvatarPhoto, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarPhoto.Get(), o.AvatarPhoto.IsSet()
}

// HasAvatarPhoto returns a boolean if a field has been set.
func (o *User) HasAvatarPhoto() bool {
	if o != nil && o.AvatarPhoto.IsSet() {
		return true
	}

	return false
}

// SetAvatarPhoto gets a reference to the given NullableUserAvatarPhoto and assigns it to the AvatarPhoto field.
func (o *User) SetAvatarPhoto(v UserAvatarPhoto) {
	o.AvatarPhoto.Set(&v)
}
// SetAvatarPhotoNil sets the value for AvatarPhoto to be an explicit nil
func (o *User) SetAvatarPhotoNil() {
	o.AvatarPhoto.Set(nil)
}

// UnsetAvatarPhoto ensures that no value is present for AvatarPhoto, not even an explicit nil
func (o *User) UnsetAvatarPhoto() {
	o.AvatarPhoto.Unset()
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *User) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *User) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *User) SetRoles(v []string) {
	o.Roles = v
}

// GetDisabledAt returns the DisabledAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetDisabledAt() time.Time {
	if o == nil || IsNil(o.DisabledAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DisabledAt.Get()
}

// GetDisabledAtOk returns a tuple with the DisabledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetDisabledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisabledAt.Get(), o.DisabledAt.IsSet()
}

// HasDisabledAt returns a boolean if a field has been set.
func (o *User) HasDisabledAt() bool {
	if o != nil && o.DisabledAt.IsSet() {
		return true
	}

	return false
}

// SetDisabledAt gets a reference to the given NullableTime and assigns it to the DisabledAt field.
func (o *User) SetDisabledAt(v time.Time) {
	o.DisabledAt.Set(&v)
}
// SetDisabledAtNil sets the value for DisabledAt to be an explicit nil
func (o *User) SetDisabledAtNil() {
	o.DisabledAt.Set(nil)
}

// UnsetDisabledAt ensures that no value is present for DisabledAt, not even an explicit nil
func (o *User) UnsetDisabledAt() {
	o.DisabledAt.Unset()
}

// GetSpamMarkedAt returns the SpamMarkedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetSpamMarkedAt() time.Time {
	if o == nil || IsNil(o.SpamMarkedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SpamMarkedAt.Get()
}

// GetSpamMarkedAtOk returns a tuple with the SpamMarkedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetSpamMarkedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpamMarkedAt.Get(), o.SpamMarkedAt.IsSet()
}

// HasSpamMarkedAt returns a boolean if a field has been set.
func (o *User) HasSpamMarkedAt() bool {
	if o != nil && o.SpamMarkedAt.IsSet() {
		return true
	}

	return false
}

// SetSpamMarkedAt gets a reference to the given NullableTime and assigns it to the SpamMarkedAt field.
func (o *User) SetSpamMarkedAt(v time.Time) {
	o.SpamMarkedAt.Set(&v)
}
// SetSpamMarkedAtNil sets the value for SpamMarkedAt to be an explicit nil
func (o *User) SetSpamMarkedAtNil() {
	o.SpamMarkedAt.Set(nil)
}

// UnsetSpamMarkedAt ensures that no value is present for SpamMarkedAt, not even an explicit nil
func (o *User) UnsetSpamMarkedAt() {
	o.SpamMarkedAt.Unset()
}

// GetSpamMarkedBy returns the SpamMarkedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetSpamMarkedBy() User {
	if o == nil || IsNil(o.SpamMarkedBy.Get()) {
		var ret User
		return ret
	}
	return *o.SpamMarkedBy.Get()
}

// GetSpamMarkedByOk returns a tuple with the SpamMarkedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetSpamMarkedByOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpamMarkedBy.Get(), o.SpamMarkedBy.IsSet()
}

// HasSpamMarkedBy returns a boolean if a field has been set.
func (o *User) HasSpamMarkedBy() bool {
	if o != nil && o.SpamMarkedBy.IsSet() {
		return true
	}

	return false
}

// SetSpamMarkedBy gets a reference to the given NullableUser and assigns it to the SpamMarkedBy field.
func (o *User) SetSpamMarkedBy(v User) {
	o.SpamMarkedBy.Set(&v)
}
// SetSpamMarkedByNil sets the value for SpamMarkedBy to be an explicit nil
func (o *User) SetSpamMarkedByNil() {
	o.SpamMarkedBy.Set(nil)
}

// UnsetSpamMarkedBy ensures that no value is present for SpamMarkedBy, not even an explicit nil
func (o *User) UnsetSpamMarkedBy() {
	o.SpamMarkedBy.Unset()
}

// GetApprovedAt returns the ApprovedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetApprovedAt() time.Time {
	if o == nil || IsNil(o.ApprovedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ApprovedAt.Get()
}

// GetApprovedAtOk returns a tuple with the ApprovedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetApprovedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApprovedAt.Get(), o.ApprovedAt.IsSet()
}

// HasApprovedAt returns a boolean if a field has been set.
func (o *User) HasApprovedAt() bool {
	if o != nil && o.ApprovedAt.IsSet() {
		return true
	}

	return false
}

// SetApprovedAt gets a reference to the given NullableTime and assigns it to the ApprovedAt field.
func (o *User) SetApprovedAt(v time.Time) {
	o.ApprovedAt.Set(&v)
}
// SetApprovedAtNil sets the value for ApprovedAt to be an explicit nil
func (o *User) SetApprovedAtNil() {
	o.ApprovedAt.Set(nil)
}

// UnsetApprovedAt ensures that no value is present for ApprovedAt, not even an explicit nil
func (o *User) UnsetApprovedAt() {
	o.ApprovedAt.Unset()
}

// GetEmailConfirmedAt returns the EmailConfirmedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetEmailConfirmedAt() time.Time {
	if o == nil || IsNil(o.EmailConfirmedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EmailConfirmedAt.Get()
}

// GetEmailConfirmedAtOk returns a tuple with the EmailConfirmedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetEmailConfirmedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailConfirmedAt.Get(), o.EmailConfirmedAt.IsSet()
}

// HasEmailConfirmedAt returns a boolean if a field has been set.
func (o *User) HasEmailConfirmedAt() bool {
	if o != nil && o.EmailConfirmedAt.IsSet() {
		return true
	}

	return false
}

// SetEmailConfirmedAt gets a reference to the given NullableTime and assigns it to the EmailConfirmedAt field.
func (o *User) SetEmailConfirmedAt(v time.Time) {
	o.EmailConfirmedAt.Set(&v)
}
// SetEmailConfirmedAtNil sets the value for EmailConfirmedAt to be an explicit nil
func (o *User) SetEmailConfirmedAtNil() {
	o.EmailConfirmedAt.Set(nil)
}

// UnsetEmailConfirmedAt ensures that no value is present for EmailConfirmedAt, not even an explicit nil
func (o *User) UnsetEmailConfirmedAt() {
	o.EmailConfirmedAt.Unset()
}

// GetCreditGrantedAt returns the CreditGrantedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetCreditGrantedAt() time.Time {
	if o == nil || IsNil(o.CreditGrantedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreditGrantedAt.Get()
}

// GetCreditGrantedAtOk returns a tuple with the CreditGrantedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetCreditGrantedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreditGrantedAt.Get(), o.CreditGrantedAt.IsSet()
}

// HasCreditGrantedAt returns a boolean if a field has been set.
func (o *User) HasCreditGrantedAt() bool {
	if o != nil && o.CreditGrantedAt.IsSet() {
		return true
	}

	return false
}

// SetCreditGrantedAt gets a reference to the given NullableTime and assigns it to the CreditGrantedAt field.
func (o *User) SetCreditGrantedAt(v time.Time) {
	o.CreditGrantedAt.Set(&v)
}
// SetCreditGrantedAtNil sets the value for CreditGrantedAt to be an explicit nil
func (o *User) SetCreditGrantedAtNil() {
	o.CreditGrantedAt.Set(nil)
}

// UnsetCreditGrantedAt ensures that no value is present for CreditGrantedAt, not even an explicit nil
func (o *User) UnsetCreditGrantedAt() {
	o.CreditGrantedAt.Unset()
}

// GetTierPin returns the TierPin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTierPin() string {
	if o == nil || IsNil(o.TierPin.Get()) {
		var ret string
		return ret
	}
	return *o.TierPin.Get()
}

// GetTierPinOk returns a tuple with the TierPin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTierPinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPin.Get(), o.TierPin.IsSet()
}

// HasTierPin returns a boolean if a field has been set.
func (o *User) HasTierPin() bool {
	if o != nil && o.TierPin.IsSet() {
		return true
	}

	return false
}

// SetTierPin gets a reference to the given NullableString and assigns it to the TierPin field.
func (o *User) SetTierPin(v string) {
	o.TierPin.Set(&v)
}
// SetTierPinNil sets the value for TierPin to be an explicit nil
func (o *User) SetTierPinNil() {
	o.TierPin.Set(nil)
}

// UnsetTierPin ensures that no value is present for TierPin, not even an explicit nil
func (o *User) UnsetTierPin() {
	o.TierPin.Unset()
}

// GetTierPinnedAt returns the TierPinnedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTierPinnedAt() time.Time {
	if o == nil || IsNil(o.TierPinnedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TierPinnedAt.Get()
}

// GetTierPinnedAtOk returns a tuple with the TierPinnedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTierPinnedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPinnedAt.Get(), o.TierPinnedAt.IsSet()
}

// HasTierPinnedAt returns a boolean if a field has been set.
func (o *User) HasTierPinnedAt() bool {
	if o != nil && o.TierPinnedAt.IsSet() {
		return true
	}

	return false
}

// SetTierPinnedAt gets a reference to the given NullableTime and assigns it to the TierPinnedAt field.
func (o *User) SetTierPinnedAt(v time.Time) {
	o.TierPinnedAt.Set(&v)
}
// SetTierPinnedAtNil sets the value for TierPinnedAt to be an explicit nil
func (o *User) SetTierPinnedAtNil() {
	o.TierPinnedAt.Set(nil)
}

// UnsetTierPinnedAt ensures that no value is present for TierPinnedAt, not even an explicit nil
func (o *User) UnsetTierPinnedAt() {
	o.TierPinnedAt.Unset()
}

// GetTierPinnedBy returns the TierPinnedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTierPinnedBy() User {
	if o == nil || IsNil(o.TierPinnedBy.Get()) {
		var ret User
		return ret
	}
	return *o.TierPinnedBy.Get()
}

// GetTierPinnedByOk returns a tuple with the TierPinnedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTierPinnedByOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPinnedBy.Get(), o.TierPinnedBy.IsSet()
}

// HasTierPinnedBy returns a boolean if a field has been set.
func (o *User) HasTierPinnedBy() bool {
	if o != nil && o.TierPinnedBy.IsSet() {
		return true
	}

	return false
}

// SetTierPinnedBy gets a reference to the given NullableUser and assigns it to the TierPinnedBy field.
func (o *User) SetTierPinnedBy(v User) {
	o.TierPinnedBy.Set(&v)
}
// SetTierPinnedByNil sets the value for TierPinnedBy to be an explicit nil
func (o *User) SetTierPinnedByNil() {
	o.TierPinnedBy.Set(nil)
}

// UnsetTierPinnedBy ensures that no value is present for TierPinnedBy, not even an explicit nil
func (o *User) UnsetTierPinnedBy() {
	o.TierPinnedBy.Unset()
}

// GetTierPinReason returns the TierPinReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTierPinReason() string {
	if o == nil || IsNil(o.TierPinReason.Get()) {
		var ret string
		return ret
	}
	return *o.TierPinReason.Get()
}

// GetTierPinReasonOk returns a tuple with the TierPinReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTierPinReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TierPinReason.Get(), o.TierPinReason.IsSet()
}

// HasTierPinReason returns a boolean if a field has been set.
func (o *User) HasTierPinReason() bool {
	if o != nil && o.TierPinReason.IsSet() {
		return true
	}

	return false
}

// SetTierPinReason gets a reference to the given NullableString and assigns it to the TierPinReason field.
func (o *User) SetTierPinReason(v string) {
	o.TierPinReason.Set(&v)
}
// SetTierPinReasonNil sets the value for TierPinReason to be an explicit nil
func (o *User) SetTierPinReasonNil() {
	o.TierPinReason.Set(nil)
}

// UnsetTierPinReason ensures that no value is present for TierPinReason, not even an explicit nil
func (o *User) UnsetTierPinReason() {
	o.TierPinReason.Unset()
}

// GetMemberships returns the Memberships field value if set, zero value otherwise.
func (o *User) GetMemberships() []Membership {
	if o == nil || IsNil(o.Memberships) {
		var ret []Membership
		return ret
	}
	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetMembershipsOk() ([]Membership, bool) {
	if o == nil || IsNil(o.Memberships) {
		return nil, false
	}
	return o.Memberships, true
}

// HasMemberships returns a boolean if a field has been set.
func (o *User) HasMemberships() bool {
	if o != nil && !IsNil(o.Memberships) {
		return true
	}

	return false
}

// SetMemberships gets a reference to the given []Membership and assigns it to the Memberships field.
func (o *User) SetMemberships(v []Membership) {
	o.Memberships = v
}

// GetOauthIdentities returns the OauthIdentities field value if set, zero value otherwise.
func (o *User) GetOauthIdentities() []OAuthIdentity {
	if o == nil || IsNil(o.OauthIdentities) {
		var ret []OAuthIdentity
		return ret
	}
	return o.OauthIdentities
}

// GetOauthIdentitiesOk returns a tuple with the OauthIdentities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOauthIdentitiesOk() ([]OAuthIdentity, bool) {
	if o == nil || IsNil(o.OauthIdentities) {
		return nil, false
	}
	return o.OauthIdentities, true
}

// HasOauthIdentities returns a boolean if a field has been set.
func (o *User) HasOauthIdentities() bool {
	if o != nil && !IsNil(o.OauthIdentities) {
		return true
	}

	return false
}

// SetOauthIdentities gets a reference to the given []OAuthIdentity and assigns it to the OauthIdentities field.
func (o *User) SetOauthIdentities(v []OAuthIdentity) {
	o.OauthIdentities = v
}

// GetTotpSecret returns the TotpSecret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTotpSecret() string {
	if o == nil || IsNil(o.TotpSecret.Get()) {
		var ret string
		return ret
	}
	return *o.TotpSecret.Get()
}

// GetTotpSecretOk returns a tuple with the TotpSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTotpSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotpSecret.Get(), o.TotpSecret.IsSet()
}

// HasTotpSecret returns a boolean if a field has been set.
func (o *User) HasTotpSecret() bool {
	if o != nil && o.TotpSecret.IsSet() {
		return true
	}

	return false
}

// SetTotpSecret gets a reference to the given NullableString and assigns it to the TotpSecret field.
func (o *User) SetTotpSecret(v string) {
	o.TotpSecret.Set(&v)
}
// SetTotpSecretNil sets the value for TotpSecret to be an explicit nil
func (o *User) SetTotpSecretNil() {
	o.TotpSecret.Set(nil)
}

// UnsetTotpSecret ensures that no value is present for TotpSecret, not even an explicit nil
func (o *User) UnsetTotpSecret() {
	o.TotpSecret.Unset()
}

// GetTotpSecretKeyId returns the TotpSecretKeyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTotpSecretKeyId() string {
	if o == nil || IsNil(o.TotpSecretKeyId.Get()) {
		var ret string
		return ret
	}
	return *o.TotpSecretKeyId.Get()
}

// GetTotpSecretKeyIdOk returns a tuple with the TotpSecretKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTotpSecretKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotpSecretKeyId.Get(), o.TotpSecretKeyId.IsSet()
}

// HasTotpSecretKeyId returns a boolean if a field has been set.
func (o *User) HasTotpSecretKeyId() bool {
	if o != nil && o.TotpSecretKeyId.IsSet() {
		return true
	}

	return false
}

// SetTotpSecretKeyId gets a reference to the given NullableString and assigns it to the TotpSecretKeyId field.
func (o *User) SetTotpSecretKeyId(v string) {
	o.TotpSecretKeyId.Set(&v)
}
// SetTotpSecretKeyIdNil sets the value for TotpSecretKeyId to be an explicit nil
func (o *User) SetTotpSecretKeyIdNil() {
	o.TotpSecretKeyId.Set(nil)
}

// UnsetTotpSecretKeyId ensures that no value is present for TotpSecretKeyId, not even an explicit nil
func (o *User) UnsetTotpSecretKeyId() {
	o.TotpSecretKeyId.Unset()
}

// GetTotpConfirmedAt returns the TotpConfirmedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTotpConfirmedAt() time.Time {
	if o == nil || IsNil(o.TotpConfirmedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TotpConfirmedAt.Get()
}

// GetTotpConfirmedAtOk returns a tuple with the TotpConfirmedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTotpConfirmedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotpConfirmedAt.Get(), o.TotpConfirmedAt.IsSet()
}

// HasTotpConfirmedAt returns a boolean if a field has been set.
func (o *User) HasTotpConfirmedAt() bool {
	if o != nil && o.TotpConfirmedAt.IsSet() {
		return true
	}

	return false
}

// SetTotpConfirmedAt gets a reference to the given NullableTime and assigns it to the TotpConfirmedAt field.
func (o *User) SetTotpConfirmedAt(v time.Time) {
	o.TotpConfirmedAt.Set(&v)
}
// SetTotpConfirmedAtNil sets the value for TotpConfirmedAt to be an explicit nil
func (o *User) SetTotpConfirmedAtNil() {
	o.TotpConfirmedAt.Set(nil)
}

// UnsetTotpConfirmedAt ensures that no value is present for TotpConfirmedAt, not even an explicit nil
func (o *User) UnsetTotpConfirmedAt() {
	o.TotpConfirmedAt.Unset()
}

// GetRecoveryCodes returns the RecoveryCodes field value if set, zero value otherwise.
func (o *User) GetRecoveryCodes() []RecoveryCode {
	if o == nil || IsNil(o.RecoveryCodes) {
		var ret []RecoveryCode
		return ret
	}
	return o.RecoveryCodes
}

// GetRecoveryCodesOk returns a tuple with the RecoveryCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRecoveryCodesOk() ([]RecoveryCode, bool) {
	if o == nil || IsNil(o.RecoveryCodes) {
		return nil, false
	}
	return o.RecoveryCodes, true
}

// HasRecoveryCodes returns a boolean if a field has been set.
func (o *User) HasRecoveryCodes() bool {
	if o != nil && !IsNil(o.RecoveryCodes) {
		return true
	}

	return false
}

// SetRecoveryCodes gets a reference to the given []RecoveryCode and assigns it to the RecoveryCodes field.
func (o *User) SetRecoveryCodes(v []RecoveryCode) {
	o.RecoveryCodes = v
}

// GetMachineFor returns the MachineFor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetMachineFor() string {
	if o == nil || IsNil(o.MachineFor.Get()) {
		var ret string
		return ret
	}
	return *o.MachineFor.Get()
}

// GetMachineForOk returns a tuple with the MachineFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetMachineForOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineFor.Get(), o.MachineFor.IsSet()
}

// HasMachineFor returns a boolean if a field has been set.
func (o *User) HasMachineFor() bool {
	if o != nil && o.MachineFor.IsSet() {
		return true
	}

	return false
}

// SetMachineFor gets a reference to the given NullableString and assigns it to the MachineFor field.
func (o *User) SetMachineFor(v string) {
	o.MachineFor.Set(&v)
}
// SetMachineForNil sets the value for MachineFor to be an explicit nil
func (o *User) SetMachineForNil() {
	o.MachineFor.Set(nil)
}

// UnsetMachineFor ensures that no value is present for MachineFor, not even an explicit nil
func (o *User) UnsetMachineFor() {
	o.MachineFor.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *User) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *User) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *User) SetId(v string) {
	o.Id = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *User) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *User) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *User) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *User) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *User) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *User) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *User) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *User) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *User) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *User) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *User) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetDisplayLabel returns the DisplayLabel field value if set, zero value otherwise.
func (o *User) GetDisplayLabel() string {
	if o == nil || IsNil(o.DisplayLabel) {
		var ret string
		return ret
	}
	return *o.DisplayLabel
}

// GetDisplayLabelOk returns a tuple with the DisplayLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDisplayLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayLabel) {
		return nil, false
	}
	return o.DisplayLabel, true
}

// HasDisplayLabel returns a boolean if a field has been set.
func (o *User) HasDisplayLabel() bool {
	if o != nil && !IsNil(o.DisplayLabel) {
		return true
	}

	return false
}

// SetDisplayLabel gets a reference to the given string and assigns it to the DisplayLabel field.
func (o *User) SetDisplayLabel(v string) {
	o.DisplayLabel = &v
}

// GetMachine returns the Machine field value if set, zero value otherwise.
func (o *User) GetMachine() bool {
	if o == nil || IsNil(o.Machine) {
		var ret bool
		return ret
	}
	return *o.Machine
}

// GetMachineOk returns a tuple with the Machine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetMachineOk() (*bool, bool) {
	if o == nil || IsNil(o.Machine) {
		return nil, false
	}
	return o.Machine, true
}

// HasMachine returns a boolean if a field has been set.
func (o *User) HasMachine() bool {
	if o != nil && !IsNil(o.Machine) {
		return true
	}

	return false
}

// SetMachine gets a reference to the given bool and assigns it to the Machine field.
func (o *User) SetMachine(v bool) {
	o.Machine = &v
}

// GetLdapManaged returns the LdapManaged field value if set, zero value otherwise.
func (o *User) GetLdapManaged() bool {
	if o == nil || IsNil(o.LdapManaged) {
		var ret bool
		return ret
	}
	return *o.LdapManaged
}

// GetLdapManagedOk returns a tuple with the LdapManaged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLdapManagedOk() (*bool, bool) {
	if o == nil || IsNil(o.LdapManaged) {
		return nil, false
	}
	return o.LdapManaged, true
}

// HasLdapManaged returns a boolean if a field has been set.
func (o *User) HasLdapManaged() bool {
	if o != nil && !IsNil(o.LdapManaged) {
		return true
	}

	return false
}

// SetLdapManaged gets a reference to the given bool and assigns it to the LdapManaged field.
func (o *User) SetLdapManaged(v bool) {
	o.LdapManaged = &v
}

// GetAvatarPhotoType returns the AvatarPhotoType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetAvatarPhotoType() string {
	if o == nil || IsNil(o.AvatarPhotoType.Get()) {
		var ret string
		return ret
	}
	return *o.AvatarPhotoType.Get()
}

// GetAvatarPhotoTypeOk returns a tuple with the AvatarPhotoType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetAvatarPhotoTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarPhotoType.Get(), o.AvatarPhotoType.IsSet()
}

// HasAvatarPhotoType returns a boolean if a field has been set.
func (o *User) HasAvatarPhotoType() bool {
	if o != nil && o.AvatarPhotoType.IsSet() {
		return true
	}

	return false
}

// SetAvatarPhotoType gets a reference to the given NullableString and assigns it to the AvatarPhotoType field.
func (o *User) SetAvatarPhotoType(v string) {
	o.AvatarPhotoType.Set(&v)
}
// SetAvatarPhotoTypeNil sets the value for AvatarPhotoType to be an explicit nil
func (o *User) SetAvatarPhotoTypeNil() {
	o.AvatarPhotoType.Set(nil)
}

// UnsetAvatarPhotoType ensures that no value is present for AvatarPhotoType, not even an explicit nil
func (o *User) UnsetAvatarPhotoType() {
	o.AvatarPhotoType.Unset()
}

// GetUserIdentifier returns the UserIdentifier field value if set, zero value otherwise.
func (o *User) GetUserIdentifier() string {
	if o == nil || IsNil(o.UserIdentifier) {
		var ret string
		return ret
	}
	return *o.UserIdentifier
}

// GetUserIdentifierOk returns a tuple with the UserIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUserIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.UserIdentifier) {
		return nil, false
	}
	return o.UserIdentifier, true
}

// HasUserIdentifier returns a boolean if a field has been set.
func (o *User) HasUserIdentifier() bool {
	if o != nil && !IsNil(o.UserIdentifier) {
		return true
	}

	return false
}

// SetUserIdentifier gets a reference to the given string and assigns it to the UserIdentifier field.
func (o *User) SetUserIdentifier(v string) {
	o.UserIdentifier = &v
}

// GetGrantedRoles returns the GrantedRoles field value if set, zero value otherwise.
func (o *User) GetGrantedRoles() []string {
	if o == nil || IsNil(o.GrantedRoles) {
		var ret []string
		return ret
	}
	return o.GrantedRoles
}

// GetGrantedRolesOk returns a tuple with the GrantedRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGrantedRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantedRoles) {
		return nil, false
	}
	return o.GrantedRoles, true
}

// HasGrantedRoles returns a boolean if a field has been set.
func (o *User) HasGrantedRoles() bool {
	if o != nil && !IsNil(o.GrantedRoles) {
		return true
	}

	return false
}

// SetGrantedRoles gets a reference to the given []string and assigns it to the GrantedRoles field.
func (o *User) SetGrantedRoles(v []string) {
	o.GrantedRoles = v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *User) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *User) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *User) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetSpam returns the Spam field value if set, zero value otherwise.
func (o *User) GetSpam() bool {
	if o == nil || IsNil(o.Spam) {
		var ret bool
		return ret
	}
	return *o.Spam
}

// GetSpamOk returns a tuple with the Spam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSpamOk() (*bool, bool) {
	if o == nil || IsNil(o.Spam) {
		return nil, false
	}
	return o.Spam, true
}

// HasSpam returns a boolean if a field has been set.
func (o *User) HasSpam() bool {
	if o != nil && !IsNil(o.Spam) {
		return true
	}

	return false
}

// SetSpam gets a reference to the given bool and assigns it to the Spam field.
func (o *User) SetSpam(v bool) {
	o.Spam = &v
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *User) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *User) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *User) SetApproved(v bool) {
	o.Approved = &v
}

// GetEmailConfirmed returns the EmailConfirmed field value if set, zero value otherwise.
func (o *User) GetEmailConfirmed() bool {
	if o == nil || IsNil(o.EmailConfirmed) {
		var ret bool
		return ret
	}
	return *o.EmailConfirmed
}

// GetEmailConfirmedOk returns a tuple with the EmailConfirmed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailConfirmedOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailConfirmed) {
		return nil, false
	}
	return o.EmailConfirmed, true
}

// HasEmailConfirmed returns a boolean if a field has been set.
func (o *User) HasEmailConfirmed() bool {
	if o != nil && !IsNil(o.EmailConfirmed) {
		return true
	}

	return false
}

// SetEmailConfirmed gets a reference to the given bool and assigns it to the EmailConfirmed field.
func (o *User) SetEmailConfirmed(v bool) {
	o.EmailConfirmed = &v
}

// GetTierPinned returns the TierPinned field value if set, zero value otherwise.
func (o *User) GetTierPinned() bool {
	if o == nil || IsNil(o.TierPinned) {
		var ret bool
		return ret
	}
	return *o.TierPinned
}

// GetTierPinnedOk returns a tuple with the TierPinned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTierPinnedOk() (*bool, bool) {
	if o == nil || IsNil(o.TierPinned) {
		return nil, false
	}
	return o.TierPinned, true
}

// HasTierPinned returns a boolean if a field has been set.
func (o *User) HasTierPinned() bool {
	if o != nil && !IsNil(o.TierPinned) {
		return true
	}

	return false
}

// SetTierPinned gets a reference to the given bool and assigns it to the TierPinned field.
func (o *User) SetTierPinned(v bool) {
	o.TierPinned = &v
}

// GetTotpEnabled returns the TotpEnabled field value if set, zero value otherwise.
func (o *User) GetTotpEnabled() bool {
	if o == nil || IsNil(o.TotpEnabled) {
		var ret bool
		return ret
	}
	return *o.TotpEnabled
}

// GetTotpEnabledOk returns a tuple with the TotpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTotpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TotpEnabled) {
		return nil, false
	}
	return o.TotpEnabled, true
}

// HasTotpEnabled returns a boolean if a field has been set.
func (o *User) HasTotpEnabled() bool {
	if o != nil && !IsNil(o.TotpEnabled) {
		return true
	}

	return false
}

// SetTotpEnabled gets a reference to the given bool and assigns it to the TotpEnabled field.
func (o *User) SetTotpEnabled(v bool) {
	o.TotpEnabled = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *User) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *User) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *User) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.Theme.IsSet() {
		toSerialize["theme"] = o.Theme.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Timezone.IsSet() {
		toSerialize["timezone"] = o.Timezone.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.LdapDn.IsSet() {
		toSerialize["ldapDn"] = o.LdapDn.Get()
	}
	if o.AvatarPhoto.IsSet() {
		toSerialize["avatarPhoto"] = o.AvatarPhoto.Get()
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if o.DisabledAt.IsSet() {
		toSerialize["disabledAt"] = o.DisabledAt.Get()
	}
	if o.SpamMarkedAt.IsSet() {
		toSerialize["spamMarkedAt"] = o.SpamMarkedAt.Get()
	}
	if o.SpamMarkedBy.IsSet() {
		toSerialize["spamMarkedBy"] = o.SpamMarkedBy.Get()
	}
	if o.ApprovedAt.IsSet() {
		toSerialize["approvedAt"] = o.ApprovedAt.Get()
	}
	if o.EmailConfirmedAt.IsSet() {
		toSerialize["emailConfirmedAt"] = o.EmailConfirmedAt.Get()
	}
	if o.CreditGrantedAt.IsSet() {
		toSerialize["creditGrantedAt"] = o.CreditGrantedAt.Get()
	}
	if o.TierPin.IsSet() {
		toSerialize["tierPin"] = o.TierPin.Get()
	}
	if o.TierPinnedAt.IsSet() {
		toSerialize["tierPinnedAt"] = o.TierPinnedAt.Get()
	}
	if o.TierPinnedBy.IsSet() {
		toSerialize["tierPinnedBy"] = o.TierPinnedBy.Get()
	}
	if o.TierPinReason.IsSet() {
		toSerialize["tierPinReason"] = o.TierPinReason.Get()
	}
	if !IsNil(o.Memberships) {
		toSerialize["memberships"] = o.Memberships
	}
	if !IsNil(o.OauthIdentities) {
		toSerialize["oauthIdentities"] = o.OauthIdentities
	}
	if o.TotpSecret.IsSet() {
		toSerialize["totpSecret"] = o.TotpSecret.Get()
	}
	if o.TotpSecretKeyId.IsSet() {
		toSerialize["totpSecretKeyId"] = o.TotpSecretKeyId.Get()
	}
	if o.TotpConfirmedAt.IsSet() {
		toSerialize["totpConfirmedAt"] = o.TotpConfirmedAt.Get()
	}
	if !IsNil(o.RecoveryCodes) {
		toSerialize["recoveryCodes"] = o.RecoveryCodes
	}
	if o.MachineFor.IsSet() {
		toSerialize["machineFor"] = o.MachineFor.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deletedAt"] = o.DeletedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if !IsNil(o.DisplayLabel) {
		toSerialize["displayLabel"] = o.DisplayLabel
	}
	if !IsNil(o.Machine) {
		toSerialize["machine"] = o.Machine
	}
	if !IsNil(o.LdapManaged) {
		toSerialize["ldapManaged"] = o.LdapManaged
	}
	if o.AvatarPhotoType.IsSet() {
		toSerialize["avatarPhotoType"] = o.AvatarPhotoType.Get()
	}
	if !IsNil(o.UserIdentifier) {
		toSerialize["userIdentifier"] = o.UserIdentifier
	}
	if !IsNil(o.GrantedRoles) {
		toSerialize["grantedRoles"] = o.GrantedRoles
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.Spam) {
		toSerialize["spam"] = o.Spam
	}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.EmailConfirmed) {
		toSerialize["emailConfirmed"] = o.EmailConfirmed
	}
	if !IsNil(o.TierPinned) {
		toSerialize["tierPinned"] = o.TierPinned
	}
	if !IsNil(o.TotpEnabled) {
		toSerialize["totpEnabled"] = o.TotpEnabled
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


