/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
)

// checks if the DeploymentVariable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentVariable{}

// DeploymentVariable struct for DeploymentVariable
type DeploymentVariable struct {
	Deployment *string `json:"deployment,omitempty"`
	VariableVersion *VariableVersion `json:"variableVersion,omitempty"`
	Id *string `json:"id,omitempty"`
	// The environment variable name this entry contributes.
	Key *string `json:"key,omitempty"`
}

// NewDeploymentVariable instantiates a new DeploymentVariable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentVariable() *DeploymentVariable {
	this := DeploymentVariable{}
	return &this
}

// NewDeploymentVariableWithDefaults instantiates a new DeploymentVariable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentVariableWithDefaults() *DeploymentVariable {
	this := DeploymentVariable{}
	return &this
}

// GetDeployment returns the Deployment field value if set, zero value otherwise.
func (o *DeploymentVariable) GetDeployment() string {
	if o == nil || IsNil(o.Deployment) {
		var ret string
		return ret
	}
	return *o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentVariable) GetDeploymentOk() (*string, bool) {
	if o == nil || IsNil(o.Deployment) {
		return nil, false
	}
	return o.Deployment, true
}

// HasDeployment returns a boolean if a field has been set.
func (o *DeploymentVariable) HasDeployment() bool {
	if o != nil && !IsNil(o.Deployment) {
		return true
	}

	return false
}

// SetDeployment gets a reference to the given string and assigns it to the Deployment field.
func (o *DeploymentVariable) SetDeployment(v string) {
	o.Deployment = &v
}

// GetVariableVersion returns the VariableVersion field value if set, zero value otherwise.
func (o *DeploymentVariable) GetVariableVersion() VariableVersion {
	if o == nil || IsNil(o.VariableVersion) {
		var ret VariableVersion
		return ret
	}
	return *o.VariableVersion
}

// GetVariableVersionOk returns a tuple with the VariableVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentVariable) GetVariableVersionOk() (*VariableVersion, bool) {
	if o == nil || IsNil(o.VariableVersion) {
		return nil, false
	}
	return o.VariableVersion, true
}

// HasVariableVersion returns a boolean if a field has been set.
func (o *DeploymentVariable) HasVariableVersion() bool {
	if o != nil && !IsNil(o.VariableVersion) {
		return true
	}

	return false
}

// SetVariableVersion gets a reference to the given VariableVersion and assigns it to the VariableVersion field.
func (o *DeploymentVariable) SetVariableVersion(v VariableVersion) {
	o.VariableVersion = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeploymentVariable) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentVariable) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeploymentVariable) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeploymentVariable) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *DeploymentVariable) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentVariable) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *DeploymentVariable) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *DeploymentVariable) SetKey(v string) {
	o.Key = &v
}

func (o DeploymentVariable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentVariable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deployment) {
		toSerialize["deployment"] = o.Deployment
	}
	if !IsNil(o.VariableVersion) {
		toSerialize["variableVersion"] = o.VariableVersion
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return toSerialize, nil
}

type NullableDeploymentVariable struct {
	value *DeploymentVariable
	isSet bool
}

func (v NullableDeploymentVariable) Get() *DeploymentVariable {
	return v.value
}

func (v *NullableDeploymentVariable) Set(val *DeploymentVariable) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentVariable) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentVariable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentVariable(val *DeploymentVariable) *NullableDeploymentVariable {
	return &NullableDeploymentVariable{value: val, isSet: true}
}

func (v NullableDeploymentVariable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentVariable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


