/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
)

// checks if the UserAvatarPhoto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAvatarPhoto{}

// UserAvatarPhoto struct for UserAvatarPhoto
type UserAvatarPhoto struct {
	// Base64 of the raw image bytes — see {@see User::getAvatarPhoto()} for why text rather than a BLOB.
	Photo *string `json:"photo,omitempty"`
	// The media type sniffed from the bytes ({@see \\App\\Service\\DirectoryPhoto}), nullable like the old `avatar_photo_type` column was: bytes can be stored without a type, and {@see \\App\\Controller\\AvatarController} falls back to `application/octet-stream`.
	Type NullableString `json:"type,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewUserAvatarPhoto instantiates a new UserAvatarPhoto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAvatarPhoto() *UserAvatarPhoto {
	this := UserAvatarPhoto{}
	return &this
}

// NewUserAvatarPhotoWithDefaults instantiates a new UserAvatarPhoto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAvatarPhotoWithDefaults() *UserAvatarPhoto {
	this := UserAvatarPhoto{}
	return &this
}

// GetPhoto returns the Photo field value if set, zero value otherwise.
func (o *UserAvatarPhoto) GetPhoto() string {
	if o == nil || IsNil(o.Photo) {
		var ret string
		return ret
	}
	return *o.Photo
}

// GetPhotoOk returns a tuple with the Photo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAvatarPhoto) GetPhotoOk() (*string, bool) {
	if o == nil || IsNil(o.Photo) {
		return nil, false
	}
	return o.Photo, true
}

// HasPhoto returns a boolean if a field has been set.
func (o *UserAvatarPhoto) HasPhoto() bool {
	if o != nil && !IsNil(o.Photo) {
		return true
	}

	return false
}

// SetPhoto gets a reference to the given string and assigns it to the Photo field.
func (o *UserAvatarPhoto) SetPhoto(v string) {
	o.Photo = &v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAvatarPhoto) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAvatarPhoto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *UserAvatarPhoto) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *UserAvatarPhoto) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *UserAvatarPhoto) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *UserAvatarPhoto) UnsetType() {
	o.Type.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserAvatarPhoto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAvatarPhoto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserAvatarPhoto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserAvatarPhoto) SetId(v string) {
	o.Id = &v
}

func (o UserAvatarPhoto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAvatarPhoto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Photo) {
		toSerialize["photo"] = o.Photo
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableUserAvatarPhoto struct {
	value *UserAvatarPhoto
	isSet bool
}

func (v NullableUserAvatarPhoto) Get() *UserAvatarPhoto {
	return v.value
}

func (v *NullableUserAvatarPhoto) Set(val *UserAvatarPhoto) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAvatarPhoto) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAvatarPhoto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAvatarPhoto(val *UserAvatarPhoto) *NullableUserAvatarPhoto {
	return &NullableUserAvatarPhoto{value: val, isSet: true}
}

func (v NullableUserAvatarPhoto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAvatarPhoto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


