/*
someones.computer API

JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package someonescomputer

import (
	"encoding/json"
	"time"
)

// checks if the CreditTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditTransaction{}

// CreditTransaction An IMMUTABLE, append-only ledger row for an Organization's shared credit balance. A balance is never mutated in place — it's always `SUM(amountCents)` over `Succeeded` rows (see {@see CreditTransactionRepository::balanceForOrganization()}). Read-only over the API: money movement stays server-driven.  Three kinds of row, one table ({@see CreditTransactionType}):    - a **top-up** is created `Pending` before redirecting to Stripe Checkout,     keyed on `stripeCheckoutSessionId`, then flipped to `Succeeded`/`Failed`     by {@see \\App\\Controller\\StripeWebhookController};   - a **grant** and a **debit** are terminal the moment they are written, so     both are written `Succeeded` — the `Pending` default is a Stripe-webhook     state and is wrong for them — and neither has a Stripe session, which is     why `stripeCheckoutSessionId` is nullable.  A debit additionally carries the hour it bills for and the meter reading it came from, so the ledger can be checked against the usage events rather than taken on trust. One table rather than two because the balance has to be the sum of money in and money out, and a second table would make every balance read a join.
type CreditTransaction struct {
	Organization *string `json:"organization,omitempty"`
	Type *string `json:"type,omitempty"`
	Status *string `json:"status,omitempty"`
	// Signed integer amount in the smallest currency unit (cents for USD).
	AmountCents *int32 `json:"amountCents,omitempty"`
	Currency *string `json:"currency,omitempty"`
	// Stripe Checkout Session id; a top-up row is created Pending against this before redirecting. Null on a grant and on a debit, neither of which has a Stripe session — the *type* is what says which kind of row this is, not whether this column is set.
	StripeCheckoutSessionId NullableString `json:"stripeCheckoutSessionId,omitempty"`
	// The clock hour a debit bills for, truncated to the hour and stored UTC.
	UsageHour NullableTime `json:"usageHour,omitempty"`
	// Which meter wrote this row; null on every non-debit row. The other half of the unique key above, and always set on a debit — never left null the way a top-up or grant's `usageHour` is, or two debits from different meters in the same hour would stop colliding with each other but a debit from the *same* meter twice would also stop colliding with itself.
	ResourceKind NullableString `json:"resourceKind,omitempty"`
	// Resolved container-seconds this debit was computed from; null on anything but a compute debit.
	UsageSeconds NullableInt32 `json:"usageSeconds,omitempty"`
	// Containers the meter saw start and never saw stop over the billed hour.
	UnresolvedContainers NullableInt32 `json:"unresolvedContainers,omitempty"`
	UsageBytes NullableCreditTransactionUsageBytes `json:"usageBytes,omitempty"`
	EngineMillis NullableCreditTransactionEngineMillis `json:"engineMillis,omitempty"`
	// Stripe Event id that last transitioned this row; secondary idempotency guard for webhook delivery.
	StripeEventId NullableString `json:"stripeEventId,omitempty"`
	CreatedBy NullableUser `json:"createdBy,omitempty"`
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
}

// NewCreditTransaction instantiates a new CreditTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditTransaction() *CreditTransaction {
	this := CreditTransaction{}
	var status string = "pending"
	this.Status = &status
	var currency string = "usd"
	this.Currency = &currency
	return &this
}

// NewCreditTransactionWithDefaults instantiates a new CreditTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditTransactionWithDefaults() *CreditTransaction {
	this := CreditTransaction{}
	var status string = "pending"
	this.Status = &status
	var currency string = "usd"
	this.Currency = &currency
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *CreditTransaction) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *CreditTransaction) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *CreditTransaction) SetOrganization(v string) {
	o.Organization = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreditTransaction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreditTransaction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreditTransaction) SetType(v string) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreditTransaction) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreditTransaction) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreditTransaction) SetStatus(v string) {
	o.Status = &v
}

// GetAmountCents returns the AmountCents field value if set, zero value otherwise.
func (o *CreditTransaction) GetAmountCents() int32 {
	if o == nil || IsNil(o.AmountCents) {
		var ret int32
		return ret
	}
	return *o.AmountCents
}

// GetAmountCentsOk returns a tuple with the AmountCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetAmountCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountCents) {
		return nil, false
	}
	return o.AmountCents, true
}

// HasAmountCents returns a boolean if a field has been set.
func (o *CreditTransaction) HasAmountCents() bool {
	if o != nil && !IsNil(o.AmountCents) {
		return true
	}

	return false
}

// SetAmountCents gets a reference to the given int32 and assigns it to the AmountCents field.
func (o *CreditTransaction) SetAmountCents(v int32) {
	o.AmountCents = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CreditTransaction) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CreditTransaction) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CreditTransaction) SetCurrency(v string) {
	o.Currency = &v
}

// GetStripeCheckoutSessionId returns the StripeCheckoutSessionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetStripeCheckoutSessionId() string {
	if o == nil || IsNil(o.StripeCheckoutSessionId.Get()) {
		var ret string
		return ret
	}
	return *o.StripeCheckoutSessionId.Get()
}

// GetStripeCheckoutSessionIdOk returns a tuple with the StripeCheckoutSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetStripeCheckoutSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StripeCheckoutSessionId.Get(), o.StripeCheckoutSessionId.IsSet()
}

// HasStripeCheckoutSessionId returns a boolean if a field has been set.
func (o *CreditTransaction) HasStripeCheckoutSessionId() bool {
	if o != nil && o.StripeCheckoutSessionId.IsSet() {
		return true
	}

	return false
}

// SetStripeCheckoutSessionId gets a reference to the given NullableString and assigns it to the StripeCheckoutSessionId field.
func (o *CreditTransaction) SetStripeCheckoutSessionId(v string) {
	o.StripeCheckoutSessionId.Set(&v)
}
// SetStripeCheckoutSessionIdNil sets the value for StripeCheckoutSessionId to be an explicit nil
func (o *CreditTransaction) SetStripeCheckoutSessionIdNil() {
	o.StripeCheckoutSessionId.Set(nil)
}

// UnsetStripeCheckoutSessionId ensures that no value is present for StripeCheckoutSessionId, not even an explicit nil
func (o *CreditTransaction) UnsetStripeCheckoutSessionId() {
	o.StripeCheckoutSessionId.Unset()
}

// GetUsageHour returns the UsageHour field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetUsageHour() time.Time {
	if o == nil || IsNil(o.UsageHour.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UsageHour.Get()
}

// GetUsageHourOk returns a tuple with the UsageHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetUsageHourOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsageHour.Get(), o.UsageHour.IsSet()
}

// HasUsageHour returns a boolean if a field has been set.
func (o *CreditTransaction) HasUsageHour() bool {
	if o != nil && o.UsageHour.IsSet() {
		return true
	}

	return false
}

// SetUsageHour gets a reference to the given NullableTime and assigns it to the UsageHour field.
func (o *CreditTransaction) SetUsageHour(v time.Time) {
	o.UsageHour.Set(&v)
}
// SetUsageHourNil sets the value for UsageHour to be an explicit nil
func (o *CreditTransaction) SetUsageHourNil() {
	o.UsageHour.Set(nil)
}

// UnsetUsageHour ensures that no value is present for UsageHour, not even an explicit nil
func (o *CreditTransaction) UnsetUsageHour() {
	o.UsageHour.Unset()
}

// GetResourceKind returns the ResourceKind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetResourceKind() string {
	if o == nil || IsNil(o.ResourceKind.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceKind.Get()
}

// GetResourceKindOk returns a tuple with the ResourceKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetResourceKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceKind.Get(), o.ResourceKind.IsSet()
}

// HasResourceKind returns a boolean if a field has been set.
func (o *CreditTransaction) HasResourceKind() bool {
	if o != nil && o.ResourceKind.IsSet() {
		return true
	}

	return false
}

// SetResourceKind gets a reference to the given NullableString and assigns it to the ResourceKind field.
func (o *CreditTransaction) SetResourceKind(v string) {
	o.ResourceKind.Set(&v)
}
// SetResourceKindNil sets the value for ResourceKind to be an explicit nil
func (o *CreditTransaction) SetResourceKindNil() {
	o.ResourceKind.Set(nil)
}

// UnsetResourceKind ensures that no value is present for ResourceKind, not even an explicit nil
func (o *CreditTransaction) UnsetResourceKind() {
	o.ResourceKind.Unset()
}

// GetUsageSeconds returns the UsageSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetUsageSeconds() int32 {
	if o == nil || IsNil(o.UsageSeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.UsageSeconds.Get()
}

// GetUsageSecondsOk returns a tuple with the UsageSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetUsageSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsageSeconds.Get(), o.UsageSeconds.IsSet()
}

// HasUsageSeconds returns a boolean if a field has been set.
func (o *CreditTransaction) HasUsageSeconds() bool {
	if o != nil && o.UsageSeconds.IsSet() {
		return true
	}

	return false
}

// SetUsageSeconds gets a reference to the given NullableInt32 and assigns it to the UsageSeconds field.
func (o *CreditTransaction) SetUsageSeconds(v int32) {
	o.UsageSeconds.Set(&v)
}
// SetUsageSecondsNil sets the value for UsageSeconds to be an explicit nil
func (o *CreditTransaction) SetUsageSecondsNil() {
	o.UsageSeconds.Set(nil)
}

// UnsetUsageSeconds ensures that no value is present for UsageSeconds, not even an explicit nil
func (o *CreditTransaction) UnsetUsageSeconds() {
	o.UsageSeconds.Unset()
}

// GetUnresolvedContainers returns the UnresolvedContainers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetUnresolvedContainers() int32 {
	if o == nil || IsNil(o.UnresolvedContainers.Get()) {
		var ret int32
		return ret
	}
	return *o.UnresolvedContainers.Get()
}

// GetUnresolvedContainersOk returns a tuple with the UnresolvedContainers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetUnresolvedContainersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnresolvedContainers.Get(), o.UnresolvedContainers.IsSet()
}

// HasUnresolvedContainers returns a boolean if a field has been set.
func (o *CreditTransaction) HasUnresolvedContainers() bool {
	if o != nil && o.UnresolvedContainers.IsSet() {
		return true
	}

	return false
}

// SetUnresolvedContainers gets a reference to the given NullableInt32 and assigns it to the UnresolvedContainers field.
func (o *CreditTransaction) SetUnresolvedContainers(v int32) {
	o.UnresolvedContainers.Set(&v)
}
// SetUnresolvedContainersNil sets the value for UnresolvedContainers to be an explicit nil
func (o *CreditTransaction) SetUnresolvedContainersNil() {
	o.UnresolvedContainers.Set(nil)
}

// UnsetUnresolvedContainers ensures that no value is present for UnresolvedContainers, not even an explicit nil
func (o *CreditTransaction) UnsetUnresolvedContainers() {
	o.UnresolvedContainers.Unset()
}

// GetUsageBytes returns the UsageBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetUsageBytes() CreditTransactionUsageBytes {
	if o == nil || IsNil(o.UsageBytes.Get()) {
		var ret CreditTransactionUsageBytes
		return ret
	}
	return *o.UsageBytes.Get()
}

// GetUsageBytesOk returns a tuple with the UsageBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetUsageBytesOk() (*CreditTransactionUsageBytes, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsageBytes.Get(), o.UsageBytes.IsSet()
}

// HasUsageBytes returns a boolean if a field has been set.
func (o *CreditTransaction) HasUsageBytes() bool {
	if o != nil && o.UsageBytes.IsSet() {
		return true
	}

	return false
}

// SetUsageBytes gets a reference to the given NullableCreditTransactionUsageBytes and assigns it to the UsageBytes field.
func (o *CreditTransaction) SetUsageBytes(v CreditTransactionUsageBytes) {
	o.UsageBytes.Set(&v)
}
// SetUsageBytesNil sets the value for UsageBytes to be an explicit nil
func (o *CreditTransaction) SetUsageBytesNil() {
	o.UsageBytes.Set(nil)
}

// UnsetUsageBytes ensures that no value is present for UsageBytes, not even an explicit nil
func (o *CreditTransaction) UnsetUsageBytes() {
	o.UsageBytes.Unset()
}

// GetEngineMillis returns the EngineMillis field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetEngineMillis() CreditTransactionEngineMillis {
	if o == nil || IsNil(o.EngineMillis.Get()) {
		var ret CreditTransactionEngineMillis
		return ret
	}
	return *o.EngineMillis.Get()
}

// GetEngineMillisOk returns a tuple with the EngineMillis field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetEngineMillisOk() (*CreditTransactionEngineMillis, bool) {
	if o == nil {
		return nil, false
	}
	return o.EngineMillis.Get(), o.EngineMillis.IsSet()
}

// HasEngineMillis returns a boolean if a field has been set.
func (o *CreditTransaction) HasEngineMillis() bool {
	if o != nil && o.EngineMillis.IsSet() {
		return true
	}

	return false
}

// SetEngineMillis gets a reference to the given NullableCreditTransactionEngineMillis and assigns it to the EngineMillis field.
func (o *CreditTransaction) SetEngineMillis(v CreditTransactionEngineMillis) {
	o.EngineMillis.Set(&v)
}
// SetEngineMillisNil sets the value for EngineMillis to be an explicit nil
func (o *CreditTransaction) SetEngineMillisNil() {
	o.EngineMillis.Set(nil)
}

// UnsetEngineMillis ensures that no value is present for EngineMillis, not even an explicit nil
func (o *CreditTransaction) UnsetEngineMillis() {
	o.EngineMillis.Unset()
}

// GetStripeEventId returns the StripeEventId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetStripeEventId() string {
	if o == nil || IsNil(o.StripeEventId.Get()) {
		var ret string
		return ret
	}
	return *o.StripeEventId.Get()
}

// GetStripeEventIdOk returns a tuple with the StripeEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetStripeEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StripeEventId.Get(), o.StripeEventId.IsSet()
}

// HasStripeEventId returns a boolean if a field has been set.
func (o *CreditTransaction) HasStripeEventId() bool {
	if o != nil && o.StripeEventId.IsSet() {
		return true
	}

	return false
}

// SetStripeEventId gets a reference to the given NullableString and assigns it to the StripeEventId field.
func (o *CreditTransaction) SetStripeEventId(v string) {
	o.StripeEventId.Set(&v)
}
// SetStripeEventIdNil sets the value for StripeEventId to be an explicit nil
func (o *CreditTransaction) SetStripeEventIdNil() {
	o.StripeEventId.Set(nil)
}

// UnsetStripeEventId ensures that no value is present for StripeEventId, not even an explicit nil
func (o *CreditTransaction) UnsetStripeEventId() {
	o.StripeEventId.Unset()
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetCreatedBy() User {
	if o == nil || IsNil(o.CreatedBy.Get()) {
		var ret User
		return ret
	}
	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetCreatedByOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *CreditTransaction) HasCreatedBy() bool {
	if o != nil && o.CreatedBy.IsSet() {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given NullableUser and assigns it to the CreatedBy field.
func (o *CreditTransaction) SetCreatedBy(v User) {
	o.CreatedBy.Set(&v)
}
// SetCreatedByNil sets the value for CreatedBy to be an explicit nil
func (o *CreditTransaction) SetCreatedByNil() {
	o.CreatedBy.Set(nil)
}

// UnsetCreatedBy ensures that no value is present for CreatedBy, not even an explicit nil
func (o *CreditTransaction) UnsetCreatedBy() {
	o.CreatedBy.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreditTransaction) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreditTransaction) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreditTransaction) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreditTransaction) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTransaction) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreditTransaction) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CreditTransaction) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditTransaction) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditTransaction) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CreditTransaction) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *CreditTransaction) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *CreditTransaction) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *CreditTransaction) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o CreditTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.AmountCents) {
		toSerialize["amountCents"] = o.AmountCents
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if o.StripeCheckoutSessionId.IsSet() {
		toSerialize["stripeCheckoutSessionId"] = o.StripeCheckoutSessionId.Get()
	}
	if o.UsageHour.IsSet() {
		toSerialize["usageHour"] = o.UsageHour.Get()
	}
	if o.ResourceKind.IsSet() {
		toSerialize["resourceKind"] = o.ResourceKind.Get()
	}
	if o.UsageSeconds.IsSet() {
		toSerialize["usageSeconds"] = o.UsageSeconds.Get()
	}
	if o.UnresolvedContainers.IsSet() {
		toSerialize["unresolvedContainers"] = o.UnresolvedContainers.Get()
	}
	if o.UsageBytes.IsSet() {
		toSerialize["usageBytes"] = o.UsageBytes.Get()
	}
	if o.EngineMillis.IsSet() {
		toSerialize["engineMillis"] = o.EngineMillis.Get()
	}
	if o.StripeEventId.IsSet() {
		toSerialize["stripeEventId"] = o.StripeEventId.Get()
	}
	if o.CreatedBy.IsSet() {
		toSerialize["createdBy"] = o.CreatedBy.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

type NullableCreditTransaction struct {
	value *CreditTransaction
	isSet bool
}

func (v NullableCreditTransaction) Get() *CreditTransaction {
	return v.value
}

func (v *NullableCreditTransaction) Set(val *CreditTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditTransaction(val *CreditTransaction) *NullableCreditTransaction {
	return &NullableCreditTransaction{value: val, isSet: true}
}

func (v NullableCreditTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


